### ISSUE TITLE
Checkout fails with signed commits

### ISSUE THREAD

**Issue by Baschdl** [hpi-swa/Squot#101]
Checkout of a commit fails when the commit is signed.

<img width="879" alt="signedcommit" src="https://cloud.githubusercontent.com/assets/3034832/26279751/ed46957c-3dbb-11e7-9ebc-71bfa722780f.png">

**Comment by j4yk** [comment]
Can you point me to a repository that contains a signed commit and name that commit, please? Otherwise I might have to set up GPG first on my (Windows) machine to try to reproduce the issue, which might take longer than waiting for your response. ;-)

**Comment by Baschdl** [comment]
Sure, the last/second commit Baschdl/test-signing@e2660bab07c19561e64ce86992e17927b61d9c2b. Clone url: [https://github.com/Baschdl/test-signing.git](https://github.com/Baschdl/test-signing.git)

**Comment by fniephaus** [comment]
[*Meta-commentary.*](http://www.extremeprogramming.org/rules/overtime.html)

**Comment by Baschdl** [comment]
@j4yk Could you maybe add a method `isSigned` when implementing this detection of signed commits?

**Comment by j4yk** [comment]
@Baschdl sure, only in FileSystem-Git or also in Squot?

**Comment by Baschdl** [comment]
Thanks, I guess adding it to both would be best
