### ISSUE TITLE
Wrong merge-base prevents push

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/Squot#112]
In the Diff-Merge project, the merge-base algorithm detects two merge-bases, of which one is an ancestor of the other (no true merge-base). Set>>anyOne picks the incorrect one by Murphy's Law and subsequently the force-push detection infers that a force-push would be needed.

![image](https://cloud.githubusercontent.com/assets/151175/26679811/f76a7bc6-46d6-11e7-9345-91f03f740dd2.png)

The bogus merge-base is not marked as reachableFromCommonAncestor on the second visit to it.
The coloring pass stops before the bogus merge-base is colored with it because all versions in the queue are reachableFromCommonAncestor before the bogus merge-base is enqueued again.

**Comment by j4yk** [comment]
@feeds Turns out it really was the missing part of the algorithm that I briefly mentioned yesterday. Finally, I have got a test case to prove it might be necessary ;-) Although reproducing the defect in a test case was hard because at some point the hashes of the versions became important for the "ordering" in the commonAncestors Set, which determines which version is picked by `anyOne`. Of course, in the test case it would pick the correct version, but not "in reality"...

**Comment by feeds** [comment]
thanks a lot!
