### ISSUE TITLE
FileDoesNotExist when removing origin/... branches locally

### ISSUE THREAD

**Issue by Baschdl** [hpi-swa/Squot#113]
FileDoesNotExist error when removing origin/... branches locally in the branch overview
![filedoesnotexist](https://cloud.githubusercontent.com/assets/3034832/26755368/0ef83858-488c-11e7-9d34-b5cc68cd17a8.png)

**Comment by j4yk** [comment]
Funnily enough, for me it does not even work to remove a remote tracking branch. But I do not get a debugger, just nothing happens.

It is annoying that the stack traces through the FileSystem code are so long, you never see the current Squot operation without clicking "Full stack" in the debugger... could you please try to reproduce the problem and provide me with the full stack?

From what I can see in the trace above, it could also be #110

**Comment by j4yk** [comment]
What I would mostly like to know is whether this failure was reached from the object list update (SquitBrowser>>objectCacheRefresh) or from somewhere else, and from which commit it tried to read stuff (the head of the deleted branch, the head of the newly selected branch, or something else)?

**Comment by Baschdl** [comment]
Sorry, I can't reproduce the error anymore

**Comment by j4yk** [comment]
Closed together with #110
