### ISSUE TITLE
FileDoesNotExist when updating Squot

### ISSUE THREAD

**Issue by Baschdl** [hpi-swa/Squot#120]
FileDoesNotExist error when updating Squot with the self-update function
![squotupdate1](https://user-images.githubusercontent.com/3034832/27604511-c2fa422e-5b79-11e7-96a1-67358f02480e.png)
![squotupdate2](https://user-images.githubusercontent.com/3034832/27604513-c52b5646-5b79-11e7-861f-a7a7fe287045.png)

**Comment by j4yk** [comment]
Looks like #110... I'll add some logging code so next time this appears I will have something to read.

**Comment by j4yk** [comment]
As we just noticed, the problem in this case stemmed from the fact that the migration of the GitTreeEntry instance variables did not succeed. Modes were `nil` and subsequently the blob was not materialized in the memory file system cache. The global migration dictionary variable was also still present and filled...

**Comment by j4yk** [comment]
Closed together with #110
