### ISSUE TITLE
GitRepository>>hasWorkingCopy is missing

### ISSUE THREAD

**Issue by krono** [hpi-swa/Squot#137]
Maybe this?

```Smalltalk
hasWorkingCopy

	^ (self configAt: 'core.bare' ifAbsent: ['false']) gitConfigBoolean not
```

**Comment by j4yk** [comment]
Exactly. It has been forgotten during a backport from the write-to-disk-working-copy branch: https://github.com/hpi-swa/Squot/blob/feature/write-to-disk-working-copy/src/FileSystem-Git.package/GitRepository.class/instance/hasWorkingCopy.st
