### ISSUE TITLE
Switching branches causes `MessageNotUnderstood: ByteString>>nextLink`

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/Squot#140]
![image](https://user-images.githubusercontent.com/2368856/31610719-7406b6fa-b279-11e7-8d10-d295d442f077.png)

**Comment by fniephaus** [comment]
Version used: https://github.com/hpi-swa/Squot/commit/4ead7327af25491d153a7a2ed3269346ba007a9c

**Comment by fniephaus** [comment]
Problem cannot be reproduced on `develop` with patch...

**Comment by j4yk** [comment]
Indeed, Tobias modified LinkedList at some point after 5.1 so you would not have to wrap lousy elements in links yourself. The 5.1 patch makes Squot create its own wrappers.

**Comment by j4yk** [comment]
You might have to reinitialize the LogMessages list of it contains non-links in a 5.1 image.
