### ISSUE TITLE
Error when 'Creating Monticello versions as backup'

### ISSUE THREAD

**Issue by stlutz** [hpi-swa/Squot#156]
I receive an error everytime I commit changes through the Git Browser. Here is what I did:

1. Download Squeak 6.0 Alpha (17595) for Linux
2. Start Squeak
3. Get Metacello by executing:

    ```
    "Get the Metacello configuration (for Squeak users)"
    Installer gemsource
        project: 'metacello';
        addPackage: 'ConfigurationOfMetacello';
        install.

    "Bootstrap Metacello Preview, using mcz files (#'previewBootstrap' symbolic version"
    ((Smalltalk at: #ConfigurationOfMetacello) project 
      version: #'previewBootstrap') load.
  
    "Load the Preview version of Metacello from GitHub"
    (Smalltalk at: #Metacello) new
      configuration: 'MetacelloPreview';
      version: #stable;
      repository: 'github://Metacello/metacello:configuration';
      load.
  
    "Now load latest version of Metacello"
    (Smalltalk at: #Metacello) new
      baseline: 'Metacello';
      repository: 'github://Metacello/metacello:master/repository';
      get.
    (Smalltalk at: #Metacello) new
      baseline: 'Metacello';
      repository: 'github://Metacello/metacello:master/repository';
      load.
    ```
4. Install Squot via Metacello:
    ```
    Metacello new
      baseline: 'Squot';
      repository: 'github://hpi-swa/Squot:master/src';
      load.
    ```
5. Open Git Browser (Apps --> Git Browser)
6. Clone [my git repository](https://github.com/stlutz/Squeak-ActiveExpressions)
7. Start tracking the relevant package(s)
    - Choose subfolder called 'src'
    - Proceed Warning
  
        ```
        About to overwrite another object in the store
        Select Proceed to continue, or close this window to cancel the operation.
        ```
8. Commit
    - Commit Message: 'Commit Message'
    - Confirm

Now at this point (when the loading bar shows `Creating Monticello versions in the package cache as backup`), I receive the following error message: `Error: ByteString called #basicNew: with invalid argument -5`.

![Error Message](https://owncloud.hpi.de/index.php/s/jjCtE0EvbPeWWZK/download)

The state of the repository after the commit appears to be correct though (to me at least), so would it be safe to ignore those errors for now and use the Git Browser anyway?

**Comment by j4yk** [comment]
I have no time to investigate right now, but I can quickly tell you that the Monticello backup is not vital for neither Squot nor Git operations, so everything should be fine. You may want to pick a suitable frame on the stack (e.g. the one with the blue flag) and choose "Return entered value" to proceed the operation.

**Comment by j4yk** [comment]
Soo... it seems like the `folderName` in the cacheNewMonticelloVersion:message: context is too short and does not include the trailing `.package`. @stlutz Can you please confirm whether it still contains "src" (when it should have contained "NameOfThePackage.package")?

**Comment by j4yk** [comment]
Has this happened again or can I close the issue?

**Comment by stlutz** [comment]
I think the issue can be closed.

**Comment by j4yk** [comment]
Ok, I'll close it and if it happens again, anybody can create a new ticket or reopen this one.
