### ISSUE TITLE
Harmonize accept/cancel button order

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/Squot#164]
In the load/pick dialog, accept is left and cancel is right. In the save/commit dialog, accept is right and cancel is left. Comes from the Mac vs. rest of the world difference, I assume.

@fniephaus @marceltaeumel What is the preferred way in Squeak to deal with the issue of the dialog button order?

**Comment by fniephaus** [comment]
Just go with something, probably `[accept]` `[cancel]` (just like in the Monticello save dialog), and use it consistently?
