### ISSUE TITLE
Adding packages in a subfolder on Windows creates no subfolder on github

### ISSUE THREAD

**Issue by MrModder** [hpi-swa/Squot#168]
## My setup
Squeak version: 6.0alpha 17822 32 bit - Windows Trunk
OS: Windows 10 64 bit

## How to replicate the issue
1. Add the package via the Git Browser GUI
   <img width="448" alt="start tracking packages" src="https://user-images.githubusercontent.com/1346493/38428578-68c31818-39bc-11e8-8818-6d400158edad.png">
2. Select a Package (ForthS in this example) and create a folder for it.
   <img width="226" alt="folder selection" src="https://user-images.githubusercontent.com/1346493/38428695-b3ab56ba-39bc-11e8-9076-684bd0428d83.png">
3. Commit the package
   <img width="448" alt="commit" src="https://user-images.githubusercontent.com/1346493/38428816-04eeb24c-39bd-11e8-9103-33faee3db3bf.png">

As you can see, the package name now is src\ForthS.package.
If you then push this commit to Github, it will not create a folder named src, which contains the ForthS.package folder, but instead one folder named: "src\ForthS.package".
This is most likely a problem with the way Windows handles directory names, but I wasn't able to fix the issue myself, except for the workaround below.

## Current workaround
By getting access to the SquotWorkingCopy object, you can manually add the Package by using: 
<img width="446" alt="manual adding" src="https://user-images.githubusercontent.com/1346493/38429299-48e573b8-39be-11e8-961e-4ccd4e47adc5.png">
This will correctly add the package in the subfolder, but it will also produce an error when doing the initial commit with the package (the commit still works if the error is abandoned)
<img width="505" alt="messagenotunderstood" src="https://user-images.githubusercontent.com/1346493/38429608-2e61f006-39bf-11e8-9cb2-f637e981d9f5.png">
All other commits afterwards work correctly though.

**Comment by j4yk** [comment]
Please reinstall Squot from the 'develop' branch and confirm whether the problem is solved now.

**Comment by MrModder** [comment]
I first installed Squot from the master branch, which produced the error.
I just tested the develop branch and the issue seems to be gone, subfolders are now working correctly.
Thanks for the quick responses
