### ISSUE TITLE
Cherrypick to Master does not work on first commit but on all others

### ISSUE THREAD

**Issue by Jeilef** [hpi-swa/Squot#171]
When I right click on the first commit on master and select cherry-pick to master this Comes up:
![image](https://user-images.githubusercontent.com/18723935/38577760-2377e90c-3d02-11e8-9693-84988a9b07de.png)

**Comment by j4yk** [comment]
Surely I forgot to catch the corner case when the picked version does not have an ancestor. Like in #166 an empty snapshot should be taken as the base in this case.
