### ISSUE TITLE
[MNU] FSReadStream>>#next:into:startingAt:

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/Squot#177]
When checking out https://github.com/hpi-swa-teaching/SwaLint/commit/53d434885e789c818da4195f7e6b29ee462c8ad4, I get the following MNU:
![image](https://user-images.githubusercontent.com/2368856/39000580-a8cd916c-43f4-11e8-87de-25b8aafd1df6.png)

Not sure what's the best way to fix this yet...

**Comment by j4yk** [comment]
There is always another Stream message that has not been sent yet and that is missing...

**Comment by fniephaus** [comment]
I'm sure you have good reasons why `FSStream` does not inherit from `Stream`, but that's what you get in return ;)

**Comment by j4yk** [comment]
I guess I succumbed to my wish for a trait-based decomposition of streams and a clean interface. ;-) Inheriting from Stream might be a reasonable compromise, though.
