### ISSUE TITLE
SquotShadowGraph doesNotUnderstand: #definitions while converting MC package history

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [hpi-swa/Squot#206]
I tried converting ArbitraryPrecisionFloat package from http://www.squeaksource.com/ArbitraryPrecisionFl.html with this snippet:

    repository := SquitRepository onDirectory: FileSystem disk / 'Volumes' / 'PassportPro_Data' / 'Smalltalk' / 'ArbitraryPrecisionFloat'.
    packageName := 'ArbitraryPrecisionFloat'.
    historianName := 'refs/heads/import-apf'.
    SquotMonticelloConverter
      convertUpToLoadedVersionOfPackageNamed: packageName
      asHistorianNamed: historianName in: repository.
    SquotMonticelloConverterVerifier
      verifyVersionsOf: (repository historianNamed: historianName)
      ofLoadedPackageNamed: packageName.

But the process failed with debugger stack below.
If I define SquotShadowGraph>>`definitions ^ self startShadow definitions` then I can proceed, but the git repository does not seem populated...

MessageNotUnderstood: SquotShadowGraph>>definitions
17 October 2018 10:38:36.295906 pm

VM: Mac OS - Smalltalk
Image: Squeak5.3alpha [latest update: #18235]

SecurityManager state:
Restricted: false
FileAccess: true
SocketAccess: true
Working Dir /Users/nicolas/Smalltalk/Squeak/trunk
Trusted Dir /foobar/tooBar/forSqueak/bogus/
Untrusted Dir /Users/nicolas/Library/Preferences/Squeak/Internet/My Squeak/

SquotShadowGraph(Object)>>doesNotUnderstand: #definitions
	Receiver: a SquotShadowGraph
	Arguments and temporary variables: 
		aMessage: 	definitions
		exception: 	MessageNotUnderstood: SquotShadowGraph>>definitions
		resumeValue: 	nil
	Receiver's instance variables: 
		objectNames: 	a WeakIdentityKeyDictionary(a SquotPackageShadow->#() )
		objectCreators: 	a WeakIdentityKeyDictionary()
		objectCreatorSlots: 	a WeakIdentityKeyDictionary()
		shadows: 	a Dictionary(#()->a SquotPackageShadow )
		delegateRegistry: 	nil
		startName: 	#()
		startShadow: 	a SquotPackageShadow

SquotMonticelloConverterVerifier>>verify:matches:
	Receiver: a SquotMonticelloConverterVerifier
	Arguments and temporary variables: 
		aVersion: 	a SquitVersion('Take an additional guard for the excess bits when com...etc...
		aMCVersion: 	a MCVersion(ArbitraryPrecisionFloat-nice.59)
		artifactSnapshot: 	nil
		mcSnapshot: 	a MCSnapshot
		mcTraits: 	a Set()
		packageArtifact: 	a SquotLazyArtifact('ArbitraryPrecisionFloat.package')
		patch: 	nil
	Receiver's instance variables: 
		squotRepository: 	a SquitRepository
		monticelloRepository: 	a MCRepositoryGroup
		historian: 	a SquitHistorian('refs/heads/import-apf')
		pendingVersions: 	an OrderedCollection()
		pendingMCVersions: 	an OrderedCollection()
		mcPackage: 	a MCPackage(ArbitraryPrecisionFloat)
		missingMCVersions: 	a Set()

[] in SquotMonticelloConverterVerifier>>verify:
	Receiver: a SquotMonticelloConverterVerifier
	Arguments and temporary variables: 
<<error during printing>
	Receiver's instance variables: 
		squotRepository: 	a SquitRepository
		monticelloRepository: 	a MCRepositoryGroup
		historian: 	a SquitHistorian('refs/heads/import-apf')
		pendingVersions: 	an OrderedCollection()
		pendingMCVersions: 	an OrderedCollection()
		mcPackage: 	a MCPackage(ArbitraryPrecisionFloat)
		missingMCVersions: 	a Set()

BlockClosure>>ensure:
	Receiver: [closure] in SquotMonticelloConverterVerifier>>verify:
	Arguments and temporary variables: 
		aBlock: 	[closure] in SquotMonticelloConverterVerifier>>verify:
		complete: 	nil
		returnValue: 	nil
	Receiver's instance variables: 
		outerContext: 	SquotMonticelloConverterVerifier>>verify:
		startpc: 	186
		numArgs: 	0

SquotMonticelloConverterVerifier>>verify:
	Receiver: a SquotMonticelloConverterVerifier
	Arguments and temporary variables: 
<<error during printing>
	Receiver's instance variables: 
		squotRepository: 	a SquitRepository
		monticelloRepository: 	a MCRepositoryGroup
		historian: 	a SquitHistorian('refs/heads/import-apf')
		pendingVersions: 	an OrderedCollection()
		pendingMCVersions: 	an OrderedCollection()
		mcPackage: 	a MCPackage(ArbitraryPrecisionFloat)
		missingMCVersions: 	a Set()

[] in SquotMonticelloConverterVerifier>>verify:hasCorrectConversionsUpTo:whichComesFrom:
	Receiver: a SquotMonticelloConverterVerifier
	Arguments and temporary variables: 
<<error during printing>
	Receiver's instance variables: 
		squotRepository: 	a SquitRepository
		monticelloRepository: 	a MCRepositoryGroup
		historian: 	a SquitHistorian('refs/heads/import-apf')
		pendingVersions: 	an OrderedCollection()
		pendingMCVersions: 	an OrderedCollection()
		mcPackage: 	a MCPackage(ArbitraryPrecisionFloat)
		missingMCVersions: 	a Set()

BlockClosure>>on:do:
	Receiver: [closure] in SquotMonticelloConverterVerifier>>verify:hasCorrectConversionsUpTo:whichComesFrom:...etc...
	Arguments and temporary variables: 
		exceptionOrExceptionSet: 	ProgressNotification
		handlerAction: 	[closure] in [] in ByteString(String)>>displaySequentialProgress:...etc...
		handlerActive: 	true
	Receiver's instance variables: 
		outerContext: 	SquotMonticelloConverterVerifier>>verify:hasCorrectConversionsUpTo:whichComesFrom:...etc...
		startpc: 	174
		numArgs: 	0

[] in ByteString(String)>>displaySequentialProgress:
	Receiver: 'Verifying '
	Arguments and temporary variables: 
		aBlock: 	[closure] in SystemProgressMorph>>position:label:min:max:
		bar: 	[closure] in SquotMonticelloConverterVerifier>>verify:hasCorrectConversionsUpTo:whichComesFrom:...etc...
	Receiver's instance variables: 
'Verifying '
[] in [] in MorphicUIManager>>displayProgress:at:from:to:during:
	Receiver: a MorphicUIManager
	Arguments and temporary variables: 
<<error during printing>
	Receiver's instance variables: 
		builderClass: 	MorphicToolBuilder

BlockClosure>>on:do:
	Receiver: [closure] in [] in MorphicUIManager>>displayProgress:at:from:to:during:
	Arguments and temporary variables: 
		exceptionOrExceptionSet: 	ProgressNotification
		handlerAction: 	[closure] in [] in MorphicUIManager>>displayProgress:at:from:to:during:...etc...
		handlerActive: 	true
	Receiver's instance variables: 
		outerContext: 	[] in MorphicUIManager>>displayProgress:at:from:to:during:
		startpc: 	146
		numArgs: 	0

[] in MorphicUIManager>>displayProgress:at:from:to:during:
	Receiver: a MorphicUIManager
	Arguments and temporary variables: 
<<error during printing>
	Receiver's instance variables: 
		builderClass: 	MorphicToolBuilder

BlockClosure>>ensure:
	Receiver: [closure] in MorphicUIManager>>displayProgress:at:from:to:during:
	Arguments and temporary variables: 
		aBlock: 	[closure] in MorphicUIManager>>displayProgress:at:from:to:during:
		complete: 	nil
		returnValue: 	nil
	Receiver's instance variables: 
		outerContext: 	MorphicUIManager>>displayProgress:at:from:to:during:
		startpc: 	139
		numArgs: 	0

MorphicUIManager>>displayProgress:at:from:to:during:
	Receiver: a MorphicUIManager
	Arguments and temporary variables: 
		titleString: 	'Verifying '
		aPoint: 	508@332
		minVal: 	0
		maxVal: 	1
		workBlock: 	[closure] in ByteString(String)>>displaySequentialProgress:
		progress: 	[closure] in SystemProgressMorph>>position:label:min:max:
		result: 	#(nil)
	Receiver's instance variables: 
		builderClass: 	MorphicToolBuilder

ProgressInitiationException>>defaultResumeValue
	Receiver: ProgressInitiationException: 
	Arguments and temporary variables: 

	Receiver's instance variables: 
		messageText: 	nil
		tag: 	nil
		signalContext: 	ProgressInitiationException(Exception)>>signal
		handlerContext: 	nil
		outerContext: 	nil
		workBlock: 	[closure] in ByteString(String)>>displaySequentialProgress:
		maxVal: 	1
		minVal: 	0
		aPoint: 	508@332
		progressTitle: 	'Verifying '

ProgressInitiationException(Exception)>>resume
	Receiver: ProgressInitiationException: 
	Arguments and temporary variables: 

	Receiver's instance variables: 
		messageText: 	nil
		tag: 	nil
		signalContext: 	ProgressInitiationException(Exception)>>signal
		handlerContext: 	nil
		outerContext: 	nil
		workBlock: 	[closure] in ByteString(String)>>displaySequentialProgress:
		maxVal: 	1
		minVal: 	0
		aPoint: 	508@332
		progressTitle: 	'Verifying '

ProgressInitiationException>>defaultAction
	Receiver: ProgressInitiationException: 
	Arguments and temporary variables: 

	Receiver's instance variables: 
		messageText: 	nil
		tag: 	nil
		signalContext: 	ProgressInitiationException(Exception)>>signal
		handlerContext: 	nil
		outerContext: 	nil
		workBlock: 	[closure] in ByteString(String)>>displaySequentialProgress:
		maxVal: 	1
		minVal: 	0
		aPoint: 	508@332
		progressTitle: 	'Verifying '

UndefinedObject>>handleSignal:
	Receiver: nil
	Arguments and temporary variables: 
		exception: 	ProgressInitiationException: 
	Receiver's instance variables: 
nil
Context>>handleSignal:
	Receiver: BlockClosure>>on:do:
	Arguments and temporary variables: 
		exception: 	ProgressInitiationException: 
		handlerActive: 	true
		val: 	nil
	Receiver's instance variables: 
		sender: 	SmalltalkEditor(TextEditor)>>evaluateSelectionAndDo:
		pc: 	32
		stackp: 	3
		method: 	(BlockClosure>>#on:do: "a CompiledMethod(2517375)")
		closureOrNil: 	nil
		receiver: 	[closure] in SmalltalkEditor(TextEditor)>>evaluateSelectionAndDo:

ProgressInitiationException(Exception)>>signal
	Receiver: ProgressInitiationException: 
	Arguments and temporary variables: 

	Receiver's instance variables: 
		messageText: 	nil
		tag: 	nil
		signalContext: 	ProgressInitiationException(Exception)>>signal
		handlerContext: 	nil
		outerContext: 	nil
		workBlock: 	[closure] in ByteString(String)>>displaySequentialProgress:
		maxVal: 	1
		minVal: 	0
		aPoint: 	508@332
		progressTitle: 	'Verifying '

--- The full stack ---
SquotShadowGraph(Object)>>doesNotUnderstand: #definitions
SquotMonticelloConverterVerifier>>verify:matches:
[] in SquotMonticelloConverterVerifier>>verify:
BlockClosure>>ensure:
SquotMonticelloConverterVerifier>>verify:
[] in SquotMonticelloConverterVerifier>>verify:hasCorrectConversionsUpTo:whichComesFrom:
BlockClosure>>on:do:
[] in ByteString(String)>>displaySequentialProgress:
[] in [] in MorphicUIManager>>displayProgress:at:from:to:during:
BlockClosure>>on:do:
[] in MorphicUIManager>>displayProgress:at:from:to:during:
BlockClosure>>ensure:
MorphicUIManager>>displayProgress:at:from:to:during:
ProgressInitiationException>>defaultResumeValue
ProgressInitiationException(Exception)>>resume
ProgressInitiationException>>defaultAction
UndefinedObject>>handleSignal:
Context>>handleSignal:
ProgressInitiationException(Exception)>>signal
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ProgressInitiationException>>display:at:from:to:during:
ProgressInitiationException class>>display:at:from:to:during:
ProgressInitiationException class>>display:from:to:during:
ByteString(String)>>displaySequentialProgress:
SquotMonticelloConverterVerifier>>verify:hasCorrectConversionsUpTo:whichComesFrom:
SquotMonticelloConverterVerifier class>>verifyVersionsOf:ofLoadedPackageNamed:
UndefinedObject>>DoIt
Compiler>>evaluateCue:ifFail:
Compiler>>evaluateCue:ifFail:logged:
Compiler>>evaluate:in:to:environment:notifying:ifFail:logged:
[] in SmalltalkEditor(TextEditor)>>evaluateSelectionAndDo:
BlockClosure>>on:do:
SmalltalkEditor(TextEditor)>>evaluateSelectionAndDo:
SmalltalkEditor(TextEditor)>>evaluateSelection
SmalltalkEditor(TextEditor)>>doIt
-- and more not shown --

**Comment by j4yk** [comment]
@nicolas-cellier-aka-nice Please try the change in `#verify:matches:` from my commit above.

**Comment by nicolas-cellier-aka-nice** [comment]
Yes, sorry, the git repository has been populated, it's just that my git client was fooled (did not detect the change), I should have updated the report.
