### ISSUE TITLE
FSReference#copyTo: won't work on non-UTF-8-Files

### ISSUE THREAD

**Issue by LeonBein** [hpi-swa/Squot#212]
When trying to use #copyTo: on a FSRreference on for instance a .png file, an InvalidUTF8 error occurs. This seems to be due to FSStream#converter which uses a UTF8TextConverter as default.

As a developer I want to either be able specify my own converter when copying or, if there is no good reason to defaultly use an utf8 converter anyway, I want an universal converter (like no converter?) to be used as default.

**Comment by j4yk** [comment]
Indeed, the contents of files should not be interpreted at all by the file system handling. The contents should be treated as sequence of bytes by default.

This might be related to the "ascii"/"text" vs. "binary" nature of FileStreams and maybe "text" is the unfortunate default, but I dot not remember it clearly.

**Comment by j4yk** [comment]
Ah here it is: 3686fa6b87a2f475665fdd6f6319dd1103c327a3
So the copyTo: operation should put the stream in binary mode, which it apparently doesn't.

**Comment by j4yk** [comment]
The problem only appeared when one tried to copy files between two different file systems. Since you probably copied files from one GitFileSystem to another or between the disk file system and a GitFileSystem, you found the issue.
