### ISSUE TITLE
No appveyor builds?

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/Squot#219]
Hello @fniephaus,

Could you please check whether appveyor actually runs on this hpi-swa repository? The last build I found for Squot was two years ago, probably before it was adopted to hpi-swa.

Kind regards,
Jakob

**Comment by fniephaus** [comment]
Hi Jakob,
Sorry for the slow response...I've activated AppVeyor for this repository. The first builds can be found at https://ci.appveyor.com/project/hpi-swa/squot/builds/22771136.

Cheers,
Fabio

**Comment by j4yk** [comment]
Thank you!
