### ISSUE TITLE
SquotImageStore paths should not be an IdentityDictionary

### ISSUE THREAD

**Issue by marceltaeumel** [hpi-swa/Squot#221]
Instances of `PackageInfo` can be transient. Only the package name counts. It should be possible to create a new instance of `PackageInfo` and use it in the image store interface.

There might be other data structures affected.

**Comment by j4yk** [comment]
Are there any cases where you want to track objects that are equal, but distinct, and keep them under distinct paths? I cannot think of any, except when you would track some Strings (instead of StringHolders) and two of them would be edited to become equal... Or classes that implement = to leniently, but that's their fault. :-)

**Comment by marceltaeumel** [comment]
I don't think so, but that's not the point. One cannot rely on the identity of PackageInfo instances in long-living Squeak images. The package name is all that counts.

In my case, it made a debugging scenario with Squot unnecessarily challenging. 😉

**Comment by j4yk** [comment]
Hmm, I don't want to fight this change off, but in my image the PackageInfos are kept in the Environment's packageOrganizer, and if you use `PackageInfo class>>named:` you will thus always get the same instance. Is the packageOrganizer flushed somehow in your image?

**Comment by marceltaeumel** [comment]
I am free to remove and add packages with the same same to the environment's package organizer. MCPackage is similar. The object identity does not matter. Only the name, which is a string. I cannot find any checks or warnings that would prevent such actions. It would be nice if Squot could just comply with that existing behavior.

**Comment by j4yk** [comment]
Then I assume I was lucky to have never had a problem with this in the last two years... probably I only ever used `PackageInfo named: ...` and did not create new ones, except in test cases.

**Comment by marceltaeumel** [comment]
I think my concern here is at a more basic level of the system. Hmm... for example, remove a class, re-add it under the same name, then re-compile all methods in the system (*cough*) --- works just fine. 😄 ... maybe you're right.

**Comment by j4yk** [comment]
@marceltaeumel Can this be closed or have you encountered further arguments against the IdentityDictionary?

**Comment by j4yk** [comment]
Only now saw the thumbs up for the close prompt. :-D
