### ISSUE TITLE
UI issue with setting the remote branch

### ISSUE THREAD

**Issue by marceltaeumel** [hpi-swa/Squot#225]
With the Vivide project, the Git Browser asked me before the first push to choose a remote branch. With the Signals project, however, it defaults to "master", which is bad. I had to revert commits.

![squot-remote-bug](https://user-images.githubusercontent.com/5765308/55166948-5eca1600-5170-11e9-94b9-1e6de23c6cf1.png)

There is no remove configured because the "remove" entry is missing form the context menu. Yet, It defaults to "master" -- yet, I want "master-squot".

**Comment by j4yk** [comment]
The upstream branch is taken from the git config. I suppose your Vivide repository did not have an upstream branch set, but your Signals repository did. Did you clone one of them with Squot and the other with Git? Git sets the upstream automatically if you clone, IIRC.

**Comment by marceltaeumel** [comment]
Nope. If I recall it correctly, I did the same steps for Vivide and the other projects.

1. Empty folder.
2. Let Squot/Squit get all the data.
3. Choose a commit to work on.
4. Hit Commit/Push and then expect the prompt for "There is no remote branch set!"

**Comment by marceltaeumel** [comment]
I suppose the issue is that "Pull" asks you for that upstream branch and "Commit/Push" takes some default. That might be the difference. I tried "Pull" first for the Vivide project but used only "Commit" and "Push" for the others. And maybe "Merge objects" for a commit.

Anyway, the default seems to be in the Squot implementation, not the .git meta data.

**Comment by marceltaeumel** [comment]
I think I found my error. While pushing from the OS command line, I got the following message:

```
PS C:\Tools\vivide_dev\squot-cache\vivide> git push
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push origin HEAD:master-squot

To push to the branch of the same name on the remote, use

    git push origin master

To choose either option permanently, see push.default in 'git help config'.
```

From that message I learned that it is common practice to not rename remote branches when checked out locally. My bad. I didn't know that.

Since the Git Browser opened with a prepared "master" local branch, I did not think of renaming but reusing that branch for whatever I choose to work on remotely.

**Comment by j4yk** [comment]
Actually it is more complicated than that. Git has this `push.default` config option that controls which branches are pushed by default and how they are mapped to remote branches. The Smalltalk implementation currently does not look at this option. Also, it always supplies a branch to the operation, so you never do `git push origin`, but rather always `git push origin master` (sticking to the example you cited above). The current implementation looks into `branch.<name>.merge` IIRC, which is equivalent to `push.default = upstream`.

Nevertheless, I will have to take a look at this, but just didn't manage to do so.

**Comment by j4yk** [comment]
I looked this up in the code again: when you push with the Git browser, it will push to the configured remote `branch.<name>.remote` to branch `branch.<name>.merge`. If either is not set, the Git browser should offer you to set the upstream branch (which sets these two config values).

When you clone in the Git browser, it will automatically create local branches for all remote branches (the Git CLI does not do that for all branches) and associate them with their remote branches. So when you cloned with the Git browser and did not create a new branch, it should not prompt you to set the upstream branch. Also, the local branches would have the same names as their remote counterparts. If you are on "master", but want to push that to "master-squot", you have to intervene manually, and it is designed to be like that.

With that information, can you add anything about your situation?

**Comment by j4yk** [comment]
Please reopen if there is something to be done here.
