### ISSUE TITLE
Add indication for class-side methods in git browser

### ISSUE THREAD

**Issue by marceltaeumel** [hpi-swa/Squot#227]
In Squot's change/diff tools, I cannot see whether a method change affects the instance side or the class side of a class. This is especially confusing if you move a method between sides.

**Comment by j4yk** [comment]
Agreed. It just does not happen often enough to bubble to the top of the priority list.

**Comment by j4yk** [comment]
@marceltaeumel What do you think of just adding separate nodes for the metaclasses as siblings of the classes? For example:

- src/Kernel (changed)
    - Object
        - initialize (changed)
    - Object class
        - initialize (changed)

The alternative would be some kind of ornament for class methods. For example "class " prepended to the selector or " (class method)" appended to the selector. The problem with bracket ornaments is that there are already brackets for (changed),  (removed), (only different timestamp) after the selector.

Do you have any other proposals?
