### ISSUE TITLE
SquotMonticelloMergeDiff doesNotUnderstand squotChangeAsStringOrText

### ISSUE THREAD

**Issue by LeonBein** [hpi-swa/Squot#233]
When pulling this error was signaled.
Not sure how to reproduce, outer context was `SquotObjectGraphDiff#squotChangeAsStringOrText`.
In both cases that I saw, packages were removed and others added, so that is probably the cause.

**Comment by j4yk** [comment]
Merging has been refactored on the develop branch and SquotMonticelloMergeDiff was superseded by SquotPackageMerge, which implements squotChangeAsStringOrText method.
