### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by BraunTom** [hpi-swa/Squot#234]
In order to synchronize state between images it would be nice to have some kind of migrations, meaning methods that get called once after pulling a specific commit. 
This would be very helpful if you need change values of class variables or calling methods that does that for you (the only current workflow I know would be calling all other people to change it manually)

**Comment by j4yk** [comment]
In Monticello this is solved with Postload scripts. Have you tried these? You can edit them via the objects list in the lower right corner of the Git browser.

If they are not executed via the Git browser stuff, we should change that.

**Comment by BraunTom** [comment]
Did not know about this feature. Works well for me :thumbsup:
