### ISSUE TITLE
Can no longer commit after upgrade to v0.7.0

### ISSUE THREAD

**Issue by cmfcmf** [hpi-swa/Squot#235]
I have updated the Git Browser using the blue button 'self update' menu entry.
I am no longer able to commit to some of my projects. When pressing 'Commit', the following error pops up:
![grafik](https://user-images.githubusercontent.com/2145092/59016748-40ecf180-8842-11e9-8fce-38653d7e48c2.png)
I have opened explorers for the key of the first `objectNames` dictionary entry (left) and one for `anObject` (right).
@tom95 had the same issue and was able to fix it by removing and re-adding the project to the Git Browser. I am trying to avoid removing and re-adding all my projects because I have quite a few of them.

**Comment by j4yk** [comment]
Please try `SquitRepository allInstancesDo: #flushCaches`, then reopen the
Git browser. Does it help?

**Comment by cmfcmf** [comment]
> Please try `SquitRepository allInstancesDo: #flushCaches`, then reopen the Git browser. Does it help?

Unfortunately not. I receive the same error.

**Comment by j4yk** [comment]
Does the stack look like this further down?

![image](https://user-images.githubusercontent.com/151175/59063231-edad8a00-88a7-11e9-8e87-471f2d2c9de3.png)

**Comment by j4yk** [comment]
> > Please try `SquitRepository allInstancesDo: #flushCaches`, then reopen the Git browser. Does it help?
> 
> Unfortunately not. I receive the same error.

In addition, please try `SquotWorkingCopy allInstancesDo: #flushPreviouslySavedArtifacts`.

I though I already created a central method to flush all those caches with a single snippet, but seems like that is not the case.

**Comment by cmfcmf** [comment]
> Does the stack look like this further down?

<details>
<summary>yes</summary>

![grafik](https://user-images.githubusercontent.com/2145092/59105134-91904780-8933-11e9-9f8d-d50705f4e69b.png)


</details>

> In addition, please try `SquotWorkingCopy allInstancesDo: #flushPreviouslySavedArtifacts`.

That fixed it! Thank you :)

**Comment by j4yk** [comment]
I changed the postload scripts to flush the caches and pushed it to master. Do you have a backup of your image or an old one that still has the old Squot version, to test whether it now works out of the box after an upgrade?

**Comment by cmfcmf** [comment]
> Do you have a backup of your image or an old one that still has the old Squot version, to test whether it now works out of the box after an upgrade?

I'm afraid I don't have a backup.

**Comment by codeZeilen** [comment]
I just updated my local Squot and the migration went fine. (If that is any indication of whether the issue is fixed :))

**Comment by j4yk** [comment]
Yes, that suffices for me. ;-)
