### ISSUE TITLE
Capture class comment format

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#237]
## Introduction
Not sure whether this is only a feature request or rather a bug: I would like to be able to synchronize the text format of class comments when using Squot/the Git Browser. Currently, only the string representation is synchronized which can be a bit disappointing if your formatting art gets rejected or even reverted.

## Vision
It would be nice to have a solution that still looks well in the README.MD, in particular on GitHub.

## Approaches
STON does not look so well in plain (see point above), but what would be about using #printHtmlString & #asTextFromHtml? GitHub deals quite well with html tags, <i>some</i> are displayed correctly (`<b>`, `<div align=right>`), <font color="#FF00FF">others</font> are just ignored (`<u>`, `<font>`).

**Problems** with this approach would be
1. Does not produce a well-formed markdown file any longer.
 It would be possible to rename the file as README (without extension). But if I am informed correctly, GitHub will then stop any Markdown-displaying.
 On the other hand, I also wouldn't expect that a class comment like:
 ```
 The Calculator class computes formulae. Just try out and pass 2*3*4
 ```
 ... is displayed as:
 
> The Calculator class computes formulae. Just try out and pass 2*3*4

 But that's what's currently happening.

2. The assignment is not completely bijective at the moment. E. g., TextPrintIt is not distinguished from TextDoIt.  
 Though this is not perfect, I think it would be better than the current state.
 Also, this should be quite easy to fix in Trunk by specifying an additional attribute?
3. TextLink does not implement #openHtmlOn: (but as well, I don't succeed to display a real TextLink using Alt + 6 in a Squeak CodeHolder).  
 Should also be easy to implement.

Another approach would be storing the metadata separately, but I would not like this solution, as it would lower cohesion or even store redundancies.

---

I am looking forward to your opinions!

**Comment by j4yk** [comment]
I am open to any improvements, but I'm afraid that Squot is not the place to discuss or ask for them: Squot only uses Monticello's code capturing under the hood (MCDefinition and such), as far as picking up the class comments is involed. The other end are the FileTree/Cypress and Tonel formats, which would have to define an encoding for these sorts of things. The serialization and deserialization of these formats are at the core also implemented in Monticello's realm.

I suggest to take this to squeak-dev and discuss it there.

**Comment by LinqLover** [comment]
Thank you for the hint, I sent an issue to squeak-dev. Nevertheless, the README.md files are squot-specific, aren't they?

**Comment by j4yk** [comment]
No, they are not, you will find them in any FileTree repository here in GitHub. :-)

**Comment by LinqLover** [comment]
Okay, thank you :)

**Comment by j4yk** [comment]
FYI: nothing arrived at the list yet, although you stated "I sent an issue to squeak-dev"

**Comment by LinqLover** [comment]
Thank you for the information, Outlook has absorbed my mails from the weekend. Will rewrite the mail soon ...
________________________________
Von: Jakob Reschke <notifications@github.com>
Gesendet: Samstag, 3. August 2019 23:38 Uhr
An: hpi-swa/Squot <Squot@noreply.github.com>
Cc: Christoph Thiede <christoph.thiede@outlook.de>; State change <state_change@noreply.github.com>
Betreff: Re: [hpi-swa/Squot] Capture class comment format (#237)


FYI: nothing arrived at the list yet, although you stated "I sent an issue to squeak-dev"
