### ISSUE TITLE
Spike: save in workspace commits its text as a text file

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/Squot#240]
It would be a nice integration, though not exactly a Squot feature, if one could hook up a workspace to a specific file and repository (or working copy). Accepting changes in the workspace would automatically write the changes to the file and commit these changes.

This would facilitate to switch Smalltalk images easier. I have a lot of TO DO or similar workspaces that I consider precious, and so I consider the images containing them precious. When in Git I could quickly create another clone (working copy) or switch branches to work on a side project, it doesn't feel like switching the image is equally simple. Sure you can "save as" and continue working in the "fork" image, but synching back changes in these workspaces is manual work an cumbersome.

Birds perspective: I need an object repository with versioning and I want to be able to quickly sync interesting objects from multiple images (that function as working copies) with that repository. Now it sounds like a real Squot use case. :-)

**Comment by j4yk** [comment]
Meanwhile this has become rather obsolete because starting with Squeak 6.0 Workspaces become tied to a text file outside of the image anyway when you accept the text. (Unless you opt out of the behavior via a dialog or preferences.)

**Comment by LinqLover** [comment]
(fyio: Afaik this is not yet a really matured feature, and Marcel signaled to me that some kind of in-image storage might be hypothetically favorable, so no need to keep interesting from coming :D)

**Comment by LinqLover** [comment]
(Such an in-image store would likely map to normal methods in a class, though.)

**Comment by j4yk** [comment]
(Putting everything into methods is what I want to avoid with Squot basically. :-D)
