### ISSUE TITLE
Question: Updating a Squot repository via Metacello?

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#241]
Hi,

again not sure whether this is really a question about Squot but not Metacello, but I would appreciate your help in every case.

I set up a [simple repository](https://github.com/LinqLover/Squeak-TipOfTheDay) with Baseline and Squot and installed it into a fresh image using
```smalltalk
Metacello new
	baseline: 'TipOfTheDay';
	repository: 'github://LinqLover/Squeak-TipOfTheDay/packages';
	load.
```

However, when I push a new commit to the repo and execute the code above again in the fresh image, the package is not updated but the old code version remains. Even clearing my working copy or removing the whole package from the fresh image did not help with it.

What I am doing wrong, or might this even be a bug? How can I update and installed Squot repo using Metacello? Thanks in advance!

**Comment by j4yk** [comment]
It has nothing to do with Squot, but with Metacello, indeed. In my opinion, it lacks a simple update or upgrade function...

You can have a look at the self update function in the Git Browser though:

![image](https://user-images.githubusercontent.com/151175/67033963-17f53b00-f117-11e9-821b-b2d9ac98be67.png)

```smalltalk
selfUpdateFromMetacello
	"Close all instances before updating to avoid any UI glitches"
	self allInstancesDo: [:each | each changed: #close].
	(Smalltalk at: #Metacello) new
		baseline: 'Squot';
		repository: 'github://hpi-swa/Squot:', self selfUpdateBranch, '/src';
		get; load.
	"UpdateWorkingCopy loadVersion: UpdateWorkingCopy baseVersion interactive: false."
	SquitBrowser open
```

If it does not work for your repo, please let me know.

**Comment by LinqLover** [comment]
Thanks for the reply!

I think my code above is equivalent to yours; I also added the #get but the new code still is not loaded. Might the line that is commented out be relevant, or is it very specific to Squot itself?

**Comment by j4yk** [comment]
The code that is commented out is only relevant to Squot itself -- or rather it isn't since it is commented out. :-)

If the get; load combination does not work, then maybe even the self update of Squot is broken. :-(

The Metacello user guide reads like you should use the following to update your project:

```
Metacello image
	baseline: 'TipOfTheDay';
	load.
```
https://github.com/dalehenrich/metacello-work/blob/master/docs/MetacelloUserGuide.md

If it does not work, I suggest you open an issue there.

**Comment by LinqLover** [comment]
Thanks, Jakob, I tried it again without success. I opened Metacello/metacello#513.
