### ISSUE TITLE
Option to commit only package changes in current ChangeSet

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/Squot#244]
If enabled, committing should only regard the changes that are also present in the current change set. 

This would be a quick solution to ignore certain changes, by moving these to a different ChangeSet.

Problems:
- Use different tools (change sets) to manage ignored contents.
- How to make the UI nice and let it not be forgotten that one has enabled the feature... ("Why do I not see all of my changes?!?")

Opinions @marceltaeumel, @krono, @tom95, @codeZeilen, @LinqLover?

**Comment by LinqLover** [comment]
Sounds interesting (although I personally do not work with different changesets frequently). It would be nice if one could multi-select from a list of all changesets.

For the UI, here's a quick-and-hacked concept how it could look:

![image](https://user-images.githubusercontent.com/38782922/67294177-c9181e80-f4e5-11e9-8070-cc02abb71d25.png)

(Just by the way, I always have been dreaming of some summary information in this window. You could display some statistics here, maybe even run the linter in background and show warnings such as "2 halts in code left" ... :D)

**Comment by j4yk** [comment]
I opted to do the opposite feature first: #37

**Comment by j4yk** [comment]
The motivation for this was to be able to ignore unrelated changes quickly. This can be done with the "ignore" feature implemented for packages in #37. To focus on more pressing issues, I will close this one. Please reopen if anyone finds a compelling need for filtering by ChangeSet.
