### ISSUE TITLE
GitRemoteAuthenticationFailed with github private repos

### ISSUE THREAD

**Issue by stefreschke** [hpi-swa/Squot#249]
GitRemoteAuthenticationFailed when trying to add a github private repository (paid feature). The exception is thrown before the user was asked for github credentials.

**Comment by j4yk** [comment]
I cloned a private repository at least twice today without issues, so I guess this has been resolved somehow in the meantime.

**Comment by LinqLover** [comment]
Yes, I have done this quite often in recent past and it always has worked fine.
