### ISSUE TITLE
Blanks in password

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa/Squot#253]
One can enter a password with blanks at the beginning or the end. While these could be valid passwords, most of the time they arent. Maybe we should show a one time warning when submitting the password?

**Comment by j4yk** [comment]
In my opinion a clear no. No software should inspect the entered passwords and guess for glitches. It might reveal details about the password to others who can look at the screen.

Is there maybe another problem with password input that makes you wish for this kind of validation? For example, are you not prompted for the correct password immediately (I don't remember the code)?

**Comment by codeZeilen** [comment]
The password prompting is fine :) When copying the password too carlessly from a website, a newline might sneak in and break your password.

BUT: Your first argument is a good argument! I will keep the issue for further occassions to explain the rational when someone struggles with this.
