### ISSUE TITLE
DateAndTime class>fromUnixTime: extension shadows trunk method

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#255]
While updating Squot in my latest-trunk image, I noticed that the following Trunk method is shadowed by FileSystem-Git: `DateAndTime class >> #fromUnixTime:`.

Diff it:
![image](https://user-images.githubusercontent.com/38782922/72159545-e231bc80-33bc-11ea-9e0f-b4ea55171033.png)

This extension method is not even stored in an override-category! It wish this conflict could be solved so that unloading Squot does not remove this method from my image.

**Comment by j4yk** [comment]
As you can see the Trunk method was added after "my" extension (taken from Pharo actually). Can you please check whether both versions are equivalent, so we can drop the extension method from Squot?

If yes, please submit a pull request for that. If you want you can add load scripts to the package to restore the Trunk version of the method, if not I will hopefully do this, but not this week.

**Comment by LinqLover** [comment]
Yes, both implementation seem to produce the same output. I am going to create a pull request ...

**Comment by LinqLover** [comment]
Don't know if you got an email - I just created a PR. Please review it carefully :)

**Comment by j4yk** [comment]
Turns out that the fromUnixTime: implementation in Squeak 5.2 is incompatible, as it produces DateAndTime objects with an offset. This leads to different author/committer timestamps in Git and none of the commit hashes match anymore. For some reasons this shows when I run the tests myself in a Squeak 5.2 image, but it never showed in the CI.

**Comment by j4yk** [comment]
Maybe the CI machines run in a UTC timezone, so that the old implementation of fromUnixTime: does not add an offset there.

**Comment by j4yk** [comment]
Conditionally restored the override in 4c2e349ea11ac64f2c907485c3b6fd41db39a210
