### ISSUE TITLE
Show meaningfull error message when push is declined due to email privacy restrictions

### ISSUE THREAD

**Issue by jonathankreidler** [hpi-swa/Squot#264]
When pushing a new locally created branch the following error occurs:
![image](https://user-images.githubusercontent.com/64194292/82753613-6c9c1b00-9db6-11ea-8018-76fe7dd4a4c9.png)

When inspecting the `report` temp variable, you can see the "push was declined due to email privacy restrictions":
![image](https://user-images.githubusercontent.com/64194292/82753646-a53bf480-9db6-11ea-956c-e25388e03982.png)

The setting that is refered to here in the [GitHub Email settings](https://github.com/settings/emails):
![image](https://user-images.githubusercontent.com/64194292/82753671-e6cc9f80-9db6-11ea-94a0-79097baaca43.png)

**Comment by j4yk** [comment]
Makes sense to include the report object in the exception and display the report contents in a dialog eventually...
