### ISSUE TITLE
Cherry-pick repo updates?

### ISSUE THREAD

**Issue by tom95** [hpi-swa/Squot#267]
We just landed the metacello PR that adds STON as dependency to Metacello. As a consequence of this, loading Squot now prompts a conflict as the deps are not updated in the stable yet. Would it be as such possible to cherry-pick https://github.com/hpi-swa/Squot/commit/b1f1e722f42be5a51545e0bda7e54271ca856685 ?

**Comment by j4yk** [comment]
Makes sense.

**Comment by j4yk** [comment]
Released as v0.7.2

**Comment by tom95** [comment]
Perfect, thank you! :)
