### ISSUE TITLE
.properties is missing in Tonel-based repository

### ISSUE THREAD

**Issue by marceltaeumel** [hpi-swa/Squot#277]
For example, see https://github.com/hpi-swa/MessageSendRecorder/tree/master/packages

I cannot load the repository because the Tonel reader will not be chosen. In Metacello, see `MCFilesystemFetchOnlyRepository >> #isTonelRepo`.

**Comment by j4yk** [comment]
For some reason the only method in the Tonel classes that cares about the properties file is TonelRepository class>>#isFiletreeAlternateFormat: and it is not sent. Seems like the writing of the properties file is an Iceberg responsibility in Pharo, though I did not investigate.

**Comment by tom95** [comment]
The way I see it, an IceRepository will create a .properties file whenever you commit and it doesn't find one yet (see `IceRepositoryProperties class>>#fromFileReference:commitish:`, which is called from the commitish, which in turn is called when the workingcopy wants to initialize its own properties based on a reference commit).

In theory, Metacello would be able to distinguish between Tonel and Filetree repos without the .properties file as well, by checking if the package folders have a suffix (tonel just writes the name, e.g. `MessageSendRecorder` whereas Filetree writes `MessageSendRecorder.package`). I'm not sure whether this check is sufficiently reliable though, in particular with the risk of the lazy-loading of Tonel in Metacello thus potentially being triggered without need.


My suggestion for this would be to write a .properties file whenever the user does a conscious choice about the package format. I would go on to say that whenever a new package is added, Squot should refer to the .properties file and choose the respective format for the new package.

What do you think?

**Comment by marceltaeumel** [comment]
Fall back to checking ".package" suffix if there is no ".properties" file present. :-)
