### ISSUE TITLE
Feature Request: Watch or edit URL of existing remote in Remotes Browser

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#284]
ATM, I can only see that there is a remote named "origin" for the selected repository:

![image](https://user-images.githubusercontent.com/38782922/93083387-d0fb2700-f692-11ea-8062-e34a10dd3cae.png)

However, it would be great to see its URL as well or to have a button to change the URL without adding a new remote.

**Comment by j4yk** [comment]
Please check out the version on the develop branch if it satisfies your needs.

**Comment by LinqLover** [comment]
Looks great, thanks! If you had time, you could map the Enter key to accept the add remote dialog, but this is very minor. :-)

**Comment by j4yk** [comment]
But only in the bottom text entry, right? I suppose I will forget it here. Please open another issue for this.
