### ISSUE TITLE
New empty GitHub repository has two branches after initial cloning: master and main

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#293]
(Forgive me if this was already fixed, I cannot update Squot at the moment)

Since GitHub has changed the name of the default branch for new projects [1], after cloning a freshly created GitHub repository in the GitBrowser, it is displayed with three branches in total: master, main, and origin/main. This should probably be cleaned up.

[1] https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

**Comment by j4yk** [comment]
Interesting outcome of the raising language awareness, good to know. What do you think, is it time to rename the default in Squot as well yet?

For the issue at hand: do I understand it right that you cloned a repository, got main and origin/main therefore, but the HEAD in your local repository is still set to refs/heads/master without any commits on it?

Then the proper solution to this is probably to respect the HEAD ref of the remote repository during the cloning. The HEAD of a bare repository like those on GitHub is supposed to announce the default branch, so I guess this was also "main" on the wire.

**Comment by LinqLover** [comment]
> For the issue at hand: do I understand it right that you cloned a repository, got main and origin/main therefore, but the HEAD in your local repository is still set to refs/heads/master without any commits on it?

Exactly.

> Then the proper solution to this is probably to respect the HEAD ref of the remote repository during the cloning. The HEAD of a bare repository like those on GitHub is supposed to announce the default branch, so I guess this was also "main" on the wire.

Yes, this sounds reasonable.

---

> Interesting outcome of the raising language awareness, good to know. What do you think, is it time to rename the default in Squot as well yet?

Pooh, this can be a long discussion with the potential of offering three opinions to two people ... Personally, I only create repositories by cloning them from GitHub, so I don't care. From the ethical aspect, I'm not really sure whether the term "master" was always used as a racial term even without connection to "client", and "merge into master" is a phrase you can read in every second tutorial, but I'm not a native speaker or a historian either, and the least I am sure whether every possible Squot user can be convinced of this point of view, too. However, this is only my personal opinion, and in the end, I think no one else can make this decision for you ... :-)

**Comment by j4yk** [comment]
Hehe, I have no particular interest to stick with "master" and would happily change it if it makes anybody more comfortable. But the question of the right time is rather whether it would confuse anybody to change the default in Squot now, and whether it would conflict with any other tools. Probably not because as they wrote Git can work with any name, GitHub has made the switch, Squot should only determine the default when a new repository is created anyway, ... Sounds like there is no good reason to wait.

**Comment by j4yk** [comment]
The upgrade path for the Squot repository itself is probably more interesting, since "master" is the branch used in Squeak's installGitInfrastructure and it is the default self-update branch. But that's something for another issue.

**Comment by LinqLover** [comment]
Sounds good. For your last comment, also keep in mind that the selfUpdater should not break when you rename the default branch ... :-)

**Comment by LinqLover** [comment]
Here is a very similar bug, not sure whether it deserves its own issue: When cloning this repository (https://github.com/LinqLover/squeak-inbox-talk.git), a useless `master` branch with a defect upstream branch is created.

**Comment by j4yk** [comment]
When I clone that repository, I get this, which looks ok to me:

![image](https://user-images.githubusercontent.com/151175/119725107-d474be00-be6f-11eb-9cd8-f53a9a4d6468.png)

**Comment by LinqLover** [comment]
Just was able to reproduce a similar bug: Clone a project with a default branch named `main` to the filesystem using git under Ubuntu, then create a Squit repo pointing to this existing path in the Squit Browser. With the latest `develop` revision, the initial branch list I see is this one:

![image](https://user-images.githubusercontent.com/38782922/142442946-cc3d47a0-cda7-46bc-8348-1adeb27a75a5.png)

Whereas in the terminal:

```
$ git checkout ^TAB
FETCH_HEAD       HEAD             main             ORIG_HEAD        origin/HEAD      origin/main      origin/shaping   shaping
```

**Comment by LinqLover** [comment]
And btw, the context menu on the other local branches (except for `master`) are not available. I needed to overwrite the branch from the origin and hope that I did not break anything by this.

**Comment by j4yk** [comment]
Reproduced the issue. It is probably the way how a working copy is initialized via "Add project" as opposed to "Clone project".

But I do get a menu for the main branch (did not try to invoke any actions yet), so what exactly do you (don't you) see when you open the menu on your local branches?

![image](https://user-images.githubusercontent.com/151175/142500090-baac3109-cda6-4e02-93a7-0e040f0b0c85.png)

**Comment by j4yk** [comment]
Looks like I have already fixed this in November, but did not close the ticket again.

**Comment by LinqLover** [comment]
Great, thank you!
