### ISSUE TITLE
Timezone of commit timestamps in GitBrowser wrong

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#294]
This

![image](https://user-images.githubusercontent.com/38782922/95269845-91130400-083a-11eb-9bb5-82348fe19cf5.png)

does not match this

https://github.com/hpi-swa-teaching/AutoTDD/pull/14/commits/f7ccede9711804886d667f05fe880657bf3d1a03
![image](https://user-images.githubusercontent.com/38782922/95269900-b7d13a80-083a-11eb-8743-073a8cfe53b2.png)

I would prefer it if the timestamps in the GitBrowser could be displayed in the local timezone instead of UTC.

**Comment by j4yk** [comment]
Funnily, Git's own programs also disagree with each other:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/151175/147274350-674d214f-0f01-4206-8046-239569bb88bf.png">

**Comment by j4yk** [comment]
I don't know any good way to solve this except for accepting it as it is.

As you already noticed, we cannot simply convert all timestamps to the current time zone offset because then in winter all commits from the summer would look different than when you view them in summer and vice versa.

Squeak's Chronology classes seem to lack a facility to look up the offset of a past instant in a given time zone. The java.time class library introduced with Java 8 is as extensive as it is (i. e. much more extensive than Squeak Chronology) for a reason...

**Comment by j4yk** [comment]
Well, this was an interesting read: I wanted to look up how this would be solved outside of Squeak, using C.

Here is my (slightly reordered) reading trail:
* Get a lead: https://stackoverflow.com/questions/13804095/get-the-time-zone-gmt-offset-in-c
* C standard: https://en.cppreference.com/w/c/chrono/localtime
* POSIX standard:
** https://pubs.opengroup.org/onlinepubs/9699919799/functions/localtime.html#
** https://pubs.opengroup.org/onlinepubs/9699919799/functions/tzset.html
** https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08
* AIX implementation: https://developer.ibm.com/articles/au-aix-posix/
* IANA timezone database a.k.a. Olson database: https://en.wikipedia.org/wiki/Tz_database
* How Micrsoft/Windows does it:
** https://devblogs.microsoft.com/dotnet/cross-platform-time-zones-with-net-core/
** https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-localtime32-localtime64?view=msvc-170
** https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/tzset?view=msvc-170
** https://docs.microsoft.com/en-us/windows/win32/api/timezoneapi/

And the Wikipedia page even pointed me to a Squeak package maintained by Dave Lewis, so Squeak is not totally out of the loop: http://wiki.squeak.org/squeak/1076

But is another dependency really worth it? I don't think so, but maybe there is a way to use the package if it is already loaded.

**Comment by LinqLover** [comment]
Uh, this smells for exploding complexity ... Anyway, an interesting reading trail indeed ... Could we maybe just introduce a simple heuristic and display a simple warning message (something like "⚠ different timezone") next to the timestamp if its zone diverges from the current one? Or would even this detection be non-trivial? If yes, please just close this issue and let us try to forget these deep abysses ...

**Comment by j4yk** [comment]
Every piece of text that we add to that column will move _all_ commit messages further to the right. So no warning message in the timestamp column... and I do not think that it would be self-explanatory to format a single "cell" in the list differently, even if it were possible.

We could add text to the summary which is displayed in the bottom-left corner of the Git Browser and in the tooltips of the commits in the list. But note that in locales with daylight saving time, you would get this warning displayed for commits from half of each year... so it could end up being more noisy than it is useful.

**Comment by LinqLover** [comment]
Okay, what would you think about #382? No explicit mental-overloading warnings but just an omission of the timezone if it is equal to the local timezone. If you think that this still creates confusion, though, we may just close this issue as "not planned". :-)
