### ISSUE TITLE
Enable Squeak changestamps in Tonel projects

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/Squot#300]
Follow-up to https://github.com/squeak-smalltalk/squeak-tonel/pull/8.

Tonel in Squeak gained the possibility to store method and class change stamps by popular demand among Squeakers. But to enable it, there must be a special property in the package.st file of a package directory. The TonelWriter would read that file before overwriting the directory.

But Squot deletes the directory before the TonelWriter gets a chance to read the package.st file, so for Squot projects with Tonel serialization, the feature is currently out of reach. This should be changed.

Moreover the stamps feature is opt-in as far as the Tonel code is concerned. This is required because otherwise Squeakers would pollute Pharo projects by default if they contribute to them. Pharo projects would not have an opt-out property set because Pharo abandoned explicit change stamps.

But for Squeak projects, the stamps should be on by default (opt-out). There should be a way to configure this for the project, like the package format can be configured.

**Comment by j4yk** [comment]
Pharo projects will most likely also not want the Squot metadata files. So it might make sense to tie the timestamps setting to the metadata-writing setting. However, the connection would not be obvious.

**Comment by j4yk** [comment]
The user experience might be better to allow a third package format choice: next to FileTree and Tonel, there should be Tonel with timestamps. Or since this should be the Squeak default, make it FileTree, Tonel and Tonel without timestamps.

**Comment by j4yk** [comment]
Implementation-wise, the package.st properties could be absorbed into the artifact metadata (as a #tonel property that contains a sub-dictionary with the package.st dictionary, for example). But without further tweaks, the properties would be written twice then: once in the package.st and again in the .squot-contents. The property can also not be a transient property because then it would be stripped away before the artifact reaches the file store for the Git commit.

**Comment by j4yk** [comment]
Going via the metadata has a blocker: the metadata is not properly propagated via artifact diffs. That means metadata differences are neither computed, nor are they applied to the target artifacts. So when loading from Git, the new properties would not reach the working copy. The other way around, if an artifact didn't have some properties in Git yet that were added or changed in the working copy, they wouldn't be applied to the files in Git. This is a bug that needs to be fixed anyway. The metadata differences are even displayed for artifact modifications in the tools (not for merges though), but then nothing is done with them.

**Comment by j4yk** [comment]
@tom95 Please set the property for a package with the text editor, then keep using it in Squot. Are new timestamps preserved correctly now?

**Comment by j4yk** [comment]
Today I thought about adding support for such properties in Monticello, via a new kind of MCDefinition. Then you wouldn't need to use Squot to remember the property in the image. However if one just used the TonelWriter on an existing file tree, the existing property would be picked up from the package.st already. Anyway here are my thoughts:

If you copy an MCVersion with such a Definition to a repository with a storage format that does not support this definition (FileTree, .mcz, .mcd), the Definition will either vanish or cause trouble. Even if the definition would be preserved in existing formats, the problem comes again when such a version is accessed from a Squeak image that does not have Tonel loaded, and therefore also not the MCDefinition subclass.

To support "Tonel-enabled" projects with such Definitions floating around the Monticello universe, the new Definition type would have to be added to the core Monticello in Squeak trunk -- and yet it would not be supported in Pharo.

**Comment by LinqLover** [comment]
This might be a totally out-of-scope thought, but why can't we derive all method timestamps from the last commit for a method (commit timestamp & author information)? This would also reduce the metadata redundancy in the repository and make it easier to edit an `st` file from a normal text editor outside of Smalltalk.

**Comment by j4yk** [comment]
This is currently a layer of abstraction problem: the Tonel reader (or FileTree reader), which produces the MCMethodDefinitions carrying the change stamps, does not know that it reads files from "a commit" or "a Monticello version". Moreover it does not know that these alien things have an ancestry, which you would need to traverse to find the latest version that modified a particular method/class/...  Without proper caching, to do this would even be very inefficient, of course.

Last but not least, some of your change stamps would be changing when you create a new version. Squot already does quietly merge back some information from a commit that it just created (some metadata might have been added or changed by the serializer), but so far this does not modify any of the objects that the users are tracking.

From the user experience perspective I would be relaxed about that (I do not get much else in other programming languages anyway), but I suspect there are Squeakers who would not want to lose their fine-grained change stamps.

**Comment by LinqLover** [comment]
> I suspect there are Squeakers who would not want to lose their fine-grained change stamps.

Good objection, I withdraw my proposal! :-)

**Comment by j4yk** [comment]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/151175/170819430-b0ada9d0-aa80-497c-a02d-9085cb8d0645.png">

![image](https://user-images.githubusercontent.com/151175/170819516-51925d1d-97a5-481d-bec7-a1638a95c3d9.png)

**Comment by j4yk** [comment]
I will consider this as solved. If there are any problems, we can always reopen or create more specific issues.

**Comment by j4yk** [comment]
Haha, I already did, but Chrome was showing me a cached page. :-P Sorry for the noise.

**Comment by LinqLover** [comment]
> Haha, I already did, but Chrome was showing me a cached page. :-P Sorry for the noise.

More likely not Chrome's but GitHub's fault. One of the drawbacks of server-side rendering, I guess ... 😅
