### ISSUE TITLE
Doesn't work with Two-Factor auth or SSH keys

### ISSUE THREAD

**Issue by massung** [hpi-swa/Squot#304]
I have 2FA setup on GitHub, and just sending my password through isn't enough. Likewise, I have local SSH keys setup so I don't actually need to provide a password to GitHub, but Squot doesn't recognize this either.

Not sure if this is a Squot issue or something I need to setup another way?

**Comment by j4yk** [comment]
Hi @massung, you need to use an auth token as the password for HTTPS.

The Git-SSH transport is currently not implemented. Somebody would have to contribute the SSH basics for Squeak and the transport implementation calling git-receive-pack and git-upload-pack at the remote.

**Comment by j4yk** [comment]
It is also described in the readme: https://github.com/hpi-swa/Squot#notes-on-pushing-to-github Does this solve the problem for you?

**Comment by massung** [comment]
I did not see that. Thanks for pointing it out (and sorry for not seeing it before).

**Comment by j4yk** [comment]
No problem. I will close this, feel free to reopen or open another issue if you encounter any more problems with this.
