### ISSUE TITLE
`ClassDescription >> #package` silently registers new PackageInfos

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#314]
We (@marceltaeumel and me) observed that the following workflow silently generates a new package in the global package registry but the user is not asked or informed about this action:

1. Create a new system category in the image (i.e. in the System Browser, "add item" in the left pane). Let's call it `MyPackage-Core`.
2. In the Git Browser, choose a repository and select "Change tracked packages"/"Add or remove packages".

Here, two packages are registered automatically: `MyPackage` and `MyPackage-Core` (see `ClassDescription >> #package` and ``PackageInfo class >> #named:``). This is confusing and does not happen if you manually created the package `MyPackage` before.

How could a solution look like? I could imagine only instantiating pseudo-package in the mentioned method, without already registering them. When actually chosen in the `SquitPackageChooser`, this object could be actually registered in the global registry (be aware of multi-processing here, so check the registry again first). But maybe you also have a better approach. :-)

**Comment by j4yk** [comment]
Please try whether it is resolved now. After that commit I do not hit a breakpoint in PackageInfo class>>named: anymore when opening the package chooser.

**Comment by LinqLover** [comment]
Sorry for the late reply! I confirm that the issue no longer occurs (on the `develop` branch). Thank you for fixing! :-)

**Comment by LinqLover** [comment]
Shall we close this issue now or when you release the fix?

**Comment by j4yk** [comment]
If it is fixed for you on develop, I will close. :-) I release too seldom to keep all the issues open in the meantime.
