### ISSUE TITLE
Misaligned metadata JSON files

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#316]
Now that I finally have an image with an up-to-date Squot, here is another issue that has been confusing me for the last months or years ...

![image](https://user-images.githubusercontent.com/38782922/117327196-a57fb380-ae92-11eb-93ea-b0f590b09f1d.png)
![image](https://user-images.githubusercontent.com/38782922/117327232-ad3f5800-ae92-11eb-9388-839b8519fe3c.png)
![image](https://user-images.githubusercontent.com/38782922/117327257-b29ca280-ae92-11eb-817e-105bab25c14c.png)

Maybe also this one:

![image](https://user-images.githubusercontent.com/38782922/117327325-c2b48200-ae92-11eb-9c02-685ce94b2e0c.png)

See <https://stackoverflow.com/q/729692/13994294>, but most likely you already know this. :-)

Do these issues need to be fixed in Squot or in filetree? In any case, it would be great to resolve them ... :-)

**Comment by LinqLover** [comment]
I see :-)

Hm ... Why does the baseline of Squot refer to a fork of <https://github.com/svenvc/ston> which is 11 commits behind?

**Comment by LinqLover** [comment]
If you have one, you could attach an "upstream" label to this issue now. :-)

**Comment by j4yk** [comment]
What do you mean with the baseline? On the develop and latest-release branches, the baseline referes to the Squeak fork of STON:

    
		spec baseline: 'Ston' with: [
				spec
					repository: 'github://squeak-smalltalk/squeak-ston:squeak/repository'. ].

**Comment by LinqLover** [comment]
Yes, my question was: Why does Squeak use a fork of STON which is even with its origin? :-)

**Comment by j4yk** [comment]
It is not even. Do not look at the master branch, but at the squeak branch (it should arguably be made the default branch in the forked repository). For the reason of the fork, you should rather ask there, but to keep it short: the original repository's maintainer has been reluctant in the past to integrate changes that accommodate Squeak.

**Comment by j4yk** [comment]
Closing this issue since I do not want to keep it open until the upstream projects change something about the formatting. If you see anything left to do here, please reopen.
