### ISSUE TITLE
Bug: Push does not work when new upstream branch does not exist

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#321]
When my local branch does not yet have an upstream branch, Push in the Squit Browser brings up the dialog for creating the upstream branch, but I need to click the Push button a second time in order to upload my changes to this upstream branch.

**Comment by j4yk** [comment]
This "bug" was a deliberate decision to simplify the implementation of the dialog workflow. It also tells you in the initial dialog box that you will have to push again.

**Comment by LinqLover** [comment]
Oh, I must have overlooked that hint. 😅 Nevertheless, it would be more convenient if you did not need to press the button again. In the past, it was also possible ...

**Comment by j4yk** [comment]
Just because it's you... ;-)

**Comment by LinqLover** [comment]
Awww, that was nice! :-) Now it works again like a charm. 🎉
