### ISSUE TITLE
Squit Diff: Metaclasses are not shown as added/removed

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#322]
Only their children are. Inconsistently, for selectors, "addition" information is never displayed but only "removed" information. :-)

![image](https://user-images.githubusercontent.com/38782922/119020602-b7874900-b99e-11eb-986c-65df4c2e5164.png)

**Comment by j4yk** [comment]
Looks like the decision from #227 to give metaclasses their own sibling nodes was not so good after all. In addition to your observation, one can also exclude the addition of a class now, but keep the additions of metaclass methods, which creates an awkward snapshot.

The suffixes for the leave nodes are currently "inherited" from Monticello. It does not display "added" for any definitions either. You are right, though, that it is not consistent as it is.

**Comment by j4yk** [comment]
On the other hand it has always been possible to exclude the leave node for the MCClassDefinition addition only, but keep the instance-side methods, so the awkward snapshots are not a new problem introduced by these sibling nodes.

**Comment by LinqLover** [comment]
Thank you! :-)
