### ISSUE TITLE
At the time of writing this: Build is failing

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [hpi-swa/Squot#323]
The screenshot:

![изображение](https://user-images.githubusercontent.com/19966907/120405976-6737c000-c37c-11eb-9bc1-0c38e82bd023.png)

I will try to fix this, maybe. In the nearest time.

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
"#794.1 failed"

"3 days ago"

https://travis-ci.org/github/hpi-swa/Squot/jobs/772894061

```
#########################

# 2 tests did not pass: #

#########################

TestCaseSuppressingProgressDisplayTraitTest
dc534e_f55c

 ✗ #testFailingTestStillFails (3ms)
a4a9db_f55c

 ✗ #testPassingTestStillPasses (1ms)
```

"The command "smalltalkci" exited with 1.

Done. Your build exited with 1."

**Comment by j4yk** [comment]
I still have to exchange the badges with those of the GitHub actions.

**Comment by j4yk** [comment]
Made the change today.
