### ISSUE TITLE
MessageNotUnderstand for MCConflict>>#isAddition

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa/Squot#325]
So far I can not provide a full reproduction of the issue, but it occurs sporadically with the master-branch version. Attached is a screenshot of a debugger. I will add a stack trace and more information as soon as the failure occurs again.

![image (4)](https://user-images.githubusercontent.com/560608/121865155-ee325400-ccfd-11eb-9769-b76f2da7ccc4.png)

**Comment by j4yk** [comment]
So if there is a mixture of conflicts and class changes (new inst vars etc.), the pulling up of the class change to the top of the list fails because MCConflicts are not comparable with MCPatchOperations, bummer. Can you reproduce it with this information?

**Comment by LinqLover** [comment]
Problem still exists for me with `"topNodesForMerge:" : "jr 7/17/2021 19:54"`:

`classOperation` is `a MCRemoval` and `each` is `a MCConflict`.

Occurs when pulling. In case of interest, I can send you an image.

**Comment by j4yk** [comment]
Fell back to identity comparison now and added tests for the two reported cases:
* conflict in the class definition itself + addition in the methods
* removal of the class + conflict in the methods

**Comment by LinqLover** [comment]
Nice, thank you!
