### ISSUE TITLE
MessageNotUnderstood: UndefinedObject>>squotApplyTo: when Squot is patching Squot itself

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#327]
I received the following error while

1. installing Squot via the Tools menu in Squeak Trunk
2. modifying some tiny things of Squot (not related to the error) in my working copy
3. cloning the Squot repository into the image
4. configuring the tracked packages for Squot
5. choosing "switch, but keep uncommitted changes" for the `develop` branch (previously, the `master` branch was displayed as active):

<details>
<pre><code>15 June 2021 12:30:46.242527 am

VM: Win32 - Smalltalk
Image: Squeak6.0alpha [latest update: #20540]

UndefinedObject(Object)>>doesNotUnderstand: #squotApplyTo:
	Receiver: nil
	Arguments and temporary variables: 
		aMessage: 	squotApplyTo: a SquotTrackedObjectMetadata(#environment->Smalltalk #objectClassName...etc...
		exception: 	MessageNotUnderstood: UndefinedObject>>squotApplyTo:
		resumeValue: 	nil
	Receiver's instance variables: 
nil

SquotTrackedObjectMetadata>>absorbDiff:
	Receiver: a SquotTrackedObjectMetadata(#environment->Smalltalk #objectClassName->#PackageInfo #serializer...etc...
	Arguments and temporary variables: 
		aTrackedObjectMetadataDiff: 	nil
	Receiver's instance variables: 
		tally: 	3
		array: 	{#objectClassName->#PackageInfo . #serializer->#SquotCypressCodeSerializer...etc...

[] in SquotImageStore>>applyDiff:toObjectAt:
	Receiver: a SquotImageStore
	Arguments and temporary variables: 
		anArtifactDiff: 	a SquotArtifactModification 'src/FileSystem-Git.package'
		path: 	'src/FileSystem-Git.package'
		object: 	a PackageInfo(FileSystem-Git)
		graph: 	a SquotMutableObjectGraph
		metadata: 	nil
		existing: 	a SquotTrackedObjectMetadata(#environment->Smalltalk #objectClassName...etc...
	Receiver's instance variables: 
		objects: 	a Dictionary('src/BaselineOfSquot.package'->a PackageInfo(BaselineOfSq...etc...
		paths: 	an IdentityDictionary(a PackageInfo(BaselineOfSquot)->a Set('src/Baselin...etc...
		environment: 	Smalltalk
		additionalInfo: 	a Dictionary('src/BaselineOfSquot.package'->a SquotTrackedObjectMetadata...etc...
		objectRegistry: 	a SquotObjectRegistry
		objectGraphs: 	a WeakIdentityKeyDictionary(a PackageInfo(BaselineOfSquot)->a SquotMutableObjectGraph...etc...
		loadOrder: 	an OrderedCollection('src/BaselineOfSquot.package' 'src/FileSystem-G...etc...

Dictionary>>at:ifPresent:ifAbsentPut:
	Receiver: a Dictionary('src/BaselineOfSquot.package'->a SquotTrackedObjectMetadata(#environment->Smalltalk...etc...
	Arguments and temporary variables: 
		key: 	'src/FileSystem-Git.package'
		oneArgBlock: 	[closure] in SquotImageStore>>applyDiff:toObjectAt:
		absentBlock: 	[closure] in SquotImageStore>>applyDiff:toObjectAt:
		index: 	9
		value: 	nil
		element: 	'src/FileSystem-Git.package'->a SquotTrackedObjectMetadata(#environment...etc...
	Receiver's instance variables: 
		tally: 	7
		array: 	{nil . nil . nil . 'src/BaselineOfSquot.package'->a SquotTrackedObjectMetadata...etc...

SquotImageStore>>applyDiff:toObjectAt:
	Receiver: a SquotImageStore
	Arguments and temporary variables: 
		anArtifactDiff: 	a SquotArtifactModification 'src/FileSystem-Git.package'
		path: 	'src/FileSystem-Git.package'
		object: 	a PackageInfo(FileSystem-Git)
		graph: 	a SquotMutableObjectGraph
		metadata: 	nil
	Receiver's instance variables: 
		objects: 	a Dictionary('src/BaselineOfSquot.package'->a PackageInfo(BaselineOfSq...etc...
		paths: 	an IdentityDictionary(a PackageInfo(BaselineOfSquot)->a Set('src/Baselin...etc...
		environment: 	Smalltalk
		additionalInfo: 	a Dictionary('src/BaselineOfSquot.package'->a SquotTrackedObjectMetadata...etc...
		objectRegistry: 	a SquotObjectRegistry
		objectGraphs: 	a WeakIdentityKeyDictionary(a PackageInfo(BaselineOfSquot)->a SquotMutableObjectGraph...etc...
		loadOrder: 	an OrderedCollection('src/BaselineOfSquot.package' 'src/FileSystem-G...etc...

SquotArtifactModification(SquotArtifactDiff)>>applyToContainer:
	Receiver: a SquotArtifactModification 'src/FileSystem-Git.package'
	Arguments and temporary variables: 
		anObjectContainer: 	a SquotImageStore
	Receiver's instance variables: 
		left: 	'src/FileSystem-Git.package' in a SquotImageStore
		right: 	a SquotArtifact('src/FileSystem-Git.package')
		isLoadedInWorkingCopy: 	true
		diffContent: 	a SquotObjectGraphDiff (1 changed objects)
		metadataDiff: 	nil
		topNodes: 	nil
		willBeLoaded: 	true

[] in SquotImageStore>>applyDiff:
	Receiver: a SquotImageStore
	Arguments and temporary variables: 
		anArtifactDiff: 	a SquotArtifactModification 'src/FileSystem-Git.package'
	Receiver's instance variables: 
		objects: 	a Dictionary('src/BaselineOfSquot.package'->a PackageInfo(BaselineOfSq...etc...
		paths: 	an IdentityDictionary(a PackageInfo(BaselineOfSquot)->a Set('src/Baselin...etc...
		environment: 	Smalltalk
		additionalInfo: 	a Dictionary('src/BaselineOfSquot.package'->a SquotTrackedObjectMetadata...etc...
		objectRegistry: 	a SquotObjectRegistry
		objectGraphs: 	a WeakIdentityKeyDictionary(a PackageInfo(BaselineOfSquot)->a SquotMutableObjectGraph...etc...
		loadOrder: 	an OrderedCollection('src/BaselineOfSquot.package' 'src/FileSystem-G...etc...

[] in SquotActiveObjectRegistry class(DynamicVariable class)>>value:during:
	Receiver: SquotActiveObjectRegistry
	Arguments and temporary variables: 
		anObject: 	a SquotObjectRegistry
		aBlock: 	[closure] in SquotImageStore>>applyDiff:
		p: 	a Process(65746) in MorphicDebugger class>>openOn:context:label:contents:fullView:...etc...
		oldValue: 	nil
		outerScopeWasDynamic: 	false
	Receiver's instance variables: 
		superclass: 	DynamicVariable
		methodDict: 	a MethodDictionary()
		format: 	0
		instanceVariables: 	nil
		organization: 	('as yet unclassified')

		subclasses: 	nil
		name: 	#SquotActiveObjectRegistry
		classPool: 	nil
		sharedPools: 	nil
		environment: 	Smalltalk
		category: 	#'Squot-Capturing'
		hash: 	11901448

FullBlockClosure(BlockClosure)>>ensure:
	Receiver: [closure] in SquotActiveObjectRegistry class(DynamicVariable class)>>value:during:
	Arguments and temporary variables: 
		aBlock: 	[closure] in SquotActiveObjectRegistry class(DynamicVariable class)>>value:during:...etc...
		complete: 	nil
		returnValue: 	nil
	Receiver's instance variables: 
		outerContext: 	SquotActiveObjectRegistry class(DynamicVariable class)>>value:during:...etc...
		startpcOrMethod: 	([] in DynamicVariable class>>#value:during: "a CompiledBlock(...etc...
		numArgs: 	0
		receiver: 	SquotActiveObjectRegistry

SquotActiveObjectRegistry class(DynamicVariable class)>>value:during:
	Receiver: SquotActiveObjectRegistry
	Arguments and temporary variables: 
		anObject: 	a SquotObjectRegistry
		aBlock: 	[closure] in SquotImageStore>>applyDiff:
		p: 	a Process(65746) in MorphicDebugger class>>openOn:context:label:contents:fullView:...etc...
		oldValue: 	nil
		outerScopeWasDynamic: 	false
	Receiver's instance variables: 
		superclass: 	DynamicVariable
		methodDict: 	a MethodDictionary()
		format: 	0
		instanceVariables: 	nil
		organization: 	('as yet unclassified')

		subclasses: 	nil
		name: 	#SquotActiveObjectRegistry
		classPool: 	nil
		sharedPools: 	nil
		environment: 	Smalltalk
		category: 	#'Squot-Capturing'
		hash: 	11901448

SquotImageStore>>activateObjectRegistryDuring:
	Receiver: a SquotImageStore
	Arguments and temporary variables: 
		aBlock: 	[closure] in SquotImageStore>>applyDiff:
	Receiver's instance variables: 
		objects: 	a Dictionary('src/BaselineOfSquot.package'->a PackageInfo(BaselineOfSq...etc...
		paths: 	an IdentityDictionary(a PackageInfo(BaselineOfSquot)->a Set('src/Baselin...etc...
		environment: 	Smalltalk
		additionalInfo: 	a Dictionary('src/BaselineOfSquot.package'->a SquotTrackedObjectMetadata...etc...
		objectRegistry: 	a SquotObjectRegistry
		objectGraphs: 	a WeakIdentityKeyDictionary(a PackageInfo(BaselineOfSquot)->a SquotMutableObjectGraph...etc...
		loadOrder: 	an OrderedCollection('src/BaselineOfSquot.package' 'src/FileSystem-G...etc...

SquotImageStore>>applyDiff:
	Receiver: a SquotImageStore
	Arguments and temporary variables: 
		anArtifactDiff: 	a SquotArtifactModification 'src/FileSystem-Git.package'
	Receiver's instance variables: 
		objects: 	a Dictionary('src/BaselineOfSquot.package'->a PackageInfo(BaselineOfSq...etc...
		paths: 	an IdentityDictionary(a PackageInfo(BaselineOfSquot)->a Set('src/Baselin...etc...
		environment: 	Smalltalk
		additionalInfo: 	a Dictionary('src/BaselineOfSquot.package'->a SquotTrackedObjectMetadata...etc...
		objectRegistry: 	a SquotObjectRegistry
		objectGraphs: 	a WeakIdentityKeyDictionary(a PackageInfo(BaselineOfSquot)->a SquotMutableObjectGraph...etc...
		loadOrder: 	an OrderedCollection('src/BaselineOfSquot.package' 'src/FileSystem-G...etc...

SquotWorkingCopy>>applyDiff:toObjectAt:
	Receiver: Squot
	Arguments and temporary variables: 
		aSquotArtifactModification: 	a SquotArtifactModification 'src/FileSystem-Git.pac...etc...
		path: 	'src/FileSystem-Git.package'
		artifact: 	nil
	Receiver's instance variables: 
		name: 	'Squot'
		store: 	a SquotImageStore
		repository: 	a SquitRepository
		loadedHistorian: 	a SquitHistorian('refs/heads/develop')
		previousVersionId: 	nil
		previousSnapshot: 	nil
		previouslySavedArtifacts: 	a Dictionary('src/Squot.package'->a SquotLazyArtifact...etc...
		shouldStoreMetadata: 	nil
		additionalParents: 	nil
		loadedVersion: 	commit 95c11bd "Unsaved changes on master"
		newVersionMessage: 	nil
		unloadedArtifacts: 	a Dictionary(''->a SquotUnrecordedFilesArtifact('') )
		loadOrder: 	an OrderedCollection('src/BaselineOfSquot.package' 'src/FileSystem-G...etc...

SquotArtifactModification(SquotArtifactDiff)>>applyToContainer:
	Receiver: a SquotArtifactModification 'src/FileSystem-Git.package'
	Arguments and temporary variables: 
		anObjectContainer: 	Squot
	Receiver's instance variables: 
		left: 	'src/FileSystem-Git.package' in a SquotImageStore
		right: 	a SquotArtifact('src/FileSystem-Git.package')
		isLoadedInWorkingCopy: 	true
		diffContent: 	a SquotObjectGraphDiff (1 changed objects)
		metadataDiff: 	nil
		topNodes: 	nil
		willBeLoaded: 	true

SquotWorkingCopy>>applyDiff:
	Receiver: Squot
	Arguments and temporary variables: 
		anArtifactDiff: 	a SquotArtifactModification 'src/FileSystem-Git.package'
	Receiver's instance variables: 
		name: 	'Squot'
		store: 	a SquotImageStore
		repository: 	a SquitRepository
		loadedHistorian: 	a SquitHistorian('refs/heads/develop')
		previousVersionId: 	nil
		previousSnapshot: 	nil
		previouslySavedArtifacts: 	a Dictionary('src/Squot.package'->a SquotLazyArtifact...etc...
		shouldStoreMetadata: 	nil
		additionalParents: 	nil
		loadedVersion: 	commit 95c11bd "Unsaved changes on master"
		newVersionMessage: 	nil
		unloadedArtifacts: 	a Dictionary(''->a SquotUnrecordedFilesArtifact('') )
		loadOrder: 	an OrderedCollection('src/BaselineOfSquot.package' 'src/FileSystem-G...etc...

[] in SquotPatch>>privateApplyTo:diffsDoing:
	Receiver: a SquotPatch (5 diffs)
	Arguments and temporary variables: 
		anObjectContainer: 	Squot
		aBlock: 	[closure] in SquotPatch>>applyTo:displayingProgress:
		order: 	an OrderedCollection('src/VersionControl.package' 'src/Pharo-compatibili...etc...
		relevant: 	an OrderedCollection('src/Squot.package' 'src/FileSystem-Git.package'...etc...
		removed: 	#()
		each: 	'src/FileSystem-Git.package'
	Receiver's instance variables: 
		base: 	a SquotSnapshot
		patched: 	a SquotSnapshot
		diffs: 	a Dictionary('src/FileSystem-Git.package'->a SquotArtifactModification '...etc...
		loadOrderDiff: 	a DiffPatch

[] in [] in Array(Collection)>>do:displayingProgress:every:
	Receiver: #('src/Squot.package' 'src/FileSystem-Git.package' 'src/Squit.package' 'src/SquotTonel-Cor...etc...
	Arguments and temporary variables: 
		aBlock: 	[closure] in SquotPatch>>privateApplyTo:diffsDoing:
		aStringOrBlock: 	[closure] in SquotWorkingCopy>>applyPatch:
		msecs: 	20
		size: 	5
		labelBlock: 	[closure] in SquotWorkingCopy>>applyPatch:
		count: 	1
		oldLabel: 	'Updating working copy... src/FileSystem-Git.package'
		lastUpdate: 	3801162471938
		bar: 	[closure] in SystemProgressMorph>>position:label:min:max:
		each: 	'src/FileSystem-Git.package'
		newLabel: 	'Updating working copy... src/FileSystem-Git.package'
	Receiver's instance variables: 
#('src/Squot.package' 'src/FileSystem-Git.package' 'src/Squit.package' 'src/SquotTonel-Cor...etc...

Array(SequenceableCollection)>>do:
	Receiver: #('src/Squot.package' 'src/FileSystem-Git.package' 'src/Squit.package' 'src/SquotTonel-Cor...etc...
	Arguments and temporary variables: 
		aBlock: 	[closure] in [] in Array(Collection)>>do:displayingProgress:every:
		index: 	2
		indexLimiT: 	5
	Receiver's instance variables: 
#('src/Squot.package' 'src/FileSystem-Git.package' 'src/Squit.package' 'src/SquotTonel-Cor...etc...

[] in Array(Collection)>>do:displayingProgress:every:
	Receiver: #('src/Squot.package' 'src/FileSystem-Git.package' 'src/Squit.package' 'src/SquotTonel-Cor...etc...
	Arguments and temporary variables: 
		aBlock: 	[closure] in SquotPatch>>privateApplyTo:diffsDoing:
		aStringOrBlock: 	[closure] in SquotWorkingCopy>>applyPatch:
		msecs: 	20
		size: 	5
		labelBlock: 	[closure] in SquotWorkingCopy>>applyPatch:
		count: 	1
		oldLabel: 	'Updating working copy... src/FileSystem-Git.package'
		lastUpdate: 	3801162471938
		bar: 	[closure] in SystemProgressMorph>>position:label:min:max:
	Receiver's instance variables: 
#('src/Squot.package' 'src/FileSystem-Git.package' 'src/Squit.package' 'src/SquotTonel-Cor...etc...

--- The full stack ---
UndefinedObject(Object)>>doesNotUnderstand: #squotApplyTo:
SquotTrackedObjectMetadata>>absorbDiff:
[] in SquotImageStore>>applyDiff:toObjectAt:
Dictionary>>at:ifPresent:ifAbsentPut:
SquotImageStore>>applyDiff:toObjectAt:
SquotArtifactModification(SquotArtifactDiff)>>applyToContainer:
[] in SquotImageStore>>applyDiff:
[] in SquotActiveObjectRegistry class(DynamicVariable class)>>value:during:
FullBlockClosure(BlockClosure)>>ensure:
SquotActiveObjectRegistry class(DynamicVariable class)>>value:during:
SquotImageStore>>activateObjectRegistryDuring:
SquotImageStore>>applyDiff:
SquotWorkingCopy>>applyDiff:toObjectAt:
SquotArtifactModification(SquotArtifactDiff)>>applyToContainer:
SquotWorkingCopy>>applyDiff:
[] in SquotPatch>>privateApplyTo:diffsDoing:
[] in [] in Array(Collection)>>do:displayingProgress:every:
Array(SequenceableCollection)>>do:
[] in Array(Collection)>>do:displayingProgress:every:
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[] in [] in MorphicUIManager>>displayProgress:at:from:to:during:
FullBlockClosure(BlockClosure)>>on:do:
[] in MorphicUIManager>>displayProgress:at:from:to:during:
FullBlockClosure(BlockClosure)>>ensure:
MorphicUIManager>>displayProgress:at:from:to:during:
ProgressInitiationException>>defaultResumeValue
ProgressInitiationException(Exception)>>resume
ProgressInitiationException>>defaultAction
UndefinedObject>>handleSignal:
ProgressInitiationException(Exception)>>signal
ProgressInitiationException>>display:at:from:to:during:
ProgressInitiationException class>>display:at:from:to:during:
ByteString(String)>>displayProgressAt:from:to:during:
ByteString(String)>>displayProgressFrom:to:during:
Array(Collection)>>do:displayingProgress:every:
Array(Collection)>>do:displayingProgress:
SquotGUI class>>displayProgress:for:do:
SquotProgress>>display:for:do:
SquotProgress class>>display:for:do:
[] in SquotPatch>>applyTo:displayingProgress:
SquotPatch>>privateApplyTo:diffsDoing:
SquotPatch>>applyTo:displayingProgress:
SquotWorkingCopy>>applyPatch:
[] in [] in SquotWorkingCopy>>privateLoadVersion:
[] in MorphicUIManager(UIManager)>>informUser:during:
[] in [] in MorphicUIManager>>displayProgress:at:from:to:during:
FullBlockClosure(BlockClosure)>>on:do:
[] in MorphicUIManager>>displayProgress:at:from:to:during:
FullBlockClosure(BlockClosure)>>ensure:
MorphicUIManager>>displayProgress:at:from:to:during:
ProgressInitiationException>>defaultResumeValue
ProgressInitiationException(Exception)>>resume
ProgressInitiationException>>defaultAction
UndefinedObject>>handleSignal:
ProgressInitiationException(Exception)>>signal
ProgressInitiationException>>display:at:from:to:during:
ProgressInitiationException class>>display:at:from:to:during:
SystemProgressMorph class>>informUserAt:during:
MorphicUIManager>>informUserDuring:
MorphicUIManager(UIManager)>>informUser:during:
SquotGUI class>>displayStatus:during:
SquotProgress>>displayStatus:during:
-- and more not shown --
</code></pre>
</details>

As a consequence, my working copy of Squot was destroyed.

Hm, is there something like a "Rebase" feature for Squot?

**Comment by LinqLover** [comment]
I have also altered my workflow like this and received the same error again:

```diff
 1. installing Squot via the Tools menu in Squeak Trunk
 2. modifying some tiny things of Squot (not related to the error) in my working copy
 3. cloning the Squot repository into the image
 4. configuring the tracked packages for Squot
-5. choosing "switch, but keep uncommitted changes" for the develop branch (previously, the master branch was displayed as active)
+5. checking out contents manually from the latest "master" branch - but unselecting all my intended changes manually
```

**Comment by LinqLover** [comment]
Third way to reproduce the issue:

```diff
 1. installing Squot via the Tools menu in Squeak Trunk
 2. modifying some tiny things of Squot (not related to the error) in my working copy
 3. cloning the Squot repository into the image
 4. configuring the tracked packages for Squot
-5. choosing "switch, but keep uncommitted changes" for the develop branch (previously, the master branch was displayed as active)
+5. pressing the "branch" button and move uncommitted changes to the new branch
```

**Comment by LinqLover** [comment]
> 5\. choosing "switch, but keep uncommitted changes" for the `develop` branch (previously, the `master` branch was displayed as active):

Choosing "switch" instead does not work either.

**Comment by LinqLover** [comment]
My final workaround after step 4 looked like this:

5. Create new temporary MCZ of squot against my local package
6. Load `develop` version of Squot using Metacello
7. Check out `develop` branch of Squot in the git browser (this time it worked without errors!)
8. Browse my temporary MCZ and load the relevant patches from it manually

But I'm sure that there would or should be a simpler solution 😆

**Comment by j4yk** [comment]
Squot patching itself is always tricky and I am unsure whether I should make great attempts to support it better.

There is an undocumented feature for hooking up the loaded Squot to the correct branch: shift-right-click on the develop branch and click "Make this the current branch". It just changes the HEAD without loading anything. Back in 2017 this was the original behavior, but it does not make much sense on projects that are not Squot itself. :-)

Rebase is not implemented yet, only cherry-pick.

**Comment by LinqLover** [comment]
> There is an undocumented feature for hooking up the loaded Squot to the correct branch: shift-right-click on the develop branch and click "Make this the current branch". It just changes the HEAD without loading anything. Back in 2017 this was the original behavior, but it does not make much sense on projects that are not Squot itself. :-)

Ah, thank you very much! I would never have expected that holding shift actually alters the menu contents. :-) IMO this should be documented. I can use it very often when I, for instance, contribute three different fixes to a project each in a single branch but like to keep them in my working copy. Also, it's significantly faster than "switch to this branch but keep uncommitted changes". :D

**Comment by j4yk** [comment]
But it is also dangerous because it allows you to easily revert changes from previous commits without knowing it.

**Comment by j4yk** [comment]
...or slipping changes of one branch onto another branch that must not get these changes.

**Comment by LinqLover** [comment]
> But it is also dangerous because it allows you to easily revert changes from previous commits without knowing it.

How should this happen? When I check in the code the next time, I would see this, wouldn't I?

> ...or leak changes of one branch into another branch, breaking it.

This would be totally intended in my use case, but thank you for the warnings. :-)

**Comment by j4yk** [comment]
> When I check in the code the next time, I would see this, wouldn't I?

It is displayed, but I could only hope that you act appropriately. ;-)

If you have an older branch loaded and change the HEAD to a newer branch, you still have the old code loaded, so the diff you initially get when committing would revert changes from the newer branch, unless you meticulously skip the changes that you do not really want to commit.

Or let's say you made a big refactoring on one branch, but need to port over a small change that you just made and that is independent of the refactoring effort. When you change the HEAD and commit, you still have your refactoring loaded. So a) your diff on commit will be huge and b) you might forget to skip all the changes that belong to the refactoring.

**Comment by LinqLover** [comment]
Alright, thanks for the explanation!
