### ISSUE TITLE
Unify "skip this change" and "toggle whether this will be loaded"

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#329]
The triple brackets are a little bit confusing to me:

![image](https://user-images.githubusercontent.com/38782922/122746553-69f64880-d28a-11eb-95b1-5894b8ec9ef4.png)

When I select the last line in the screenshot and press <kbd>cmd</kbd> + <kbd>x</kbd>, I would have expected to un-ignore it and thus load the package when I press Accept.

**Comment by j4yk** [comment]
What do you mean by "unify"? These are two different things: skip this change will prevent that changes are applied to an artifact, which might be unloaded, while toggle load controls whether the artifact will be loaded afterwards.

If "choose this edition" would also turn on load, you could not toggle it back and forth for an unloaded artifact (think of a -Pharo platform package or so...).

**Comment by LinqLover** [comment]
Thank you, I was not aware of the different meanings. The double brackets were just a bit confusing to me. :-)
