### ISSUE TITLE
Feature Request: Show timestamp and message category in the commit dialog

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#336]
`MCSaveVersionDialog` already has this feature. I find it very helpful, for instance, in order to detect defect timestamps or make sure I am not committing unclassified methods.

**Comment by j4yk** [comment]
Mind the screen real estate. Please start by providing a picture mockup to demonstrate where this information should go.

**Comment by LinqLover** [comment]
A small two-line annotation pane below the text contents should succeed, I think. Just large enough to hold both the new and the old timestamp and category. :-)

**Comment by j4yk** [comment]
Closed through #374
