### ISSUE TITLE
Add option to disable/enable MCZ backups

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/Squot#338]
Squot exports backups in the MCZ format before a commit, which take a significant amount of time to create. While these backups are sometimes useful, it'd be great if there is an option to disable this feature to speed up the time to display the commit dialog.

**Comment by j4yk** [comment]
Looked it up: I have already removed this last year in efb7fd42eaae32b661acc4ab2624010f6e01dbe0. :-)

**Comment by fniephaus** [comment]
Great, looks like I need to update my installation :)
