### ISSUE TITLE
Commit is aborted silently because of tonel error

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#341]
Sometimes I'm wondering why no one is having so many problems with Squot like me. 😅 

Suddenly, when I press Commit, the window closes, but a commit is not generated.

If I evaluate `self createVersion` manually in `[] in [] in SquotInteractiveSave>>applyToWorkingCopy`, I get an error from tonel:  
`MessageNotUnderstood: UndefinedObject>>addAll:` from `[] in TonelWriterForFileSystem(TonelWriter)>>writePackage:`, `currentPackageProperties` is `nil` and `self currentPackageProperties` raises another error:  
`STONReaderError: At character 8: 'invalid input'`, which is probably because `git:/packages/Sandblocks-Core/package.st` in this working copy has a content (`	(self packageDir / 'package.st') readStreamDo: [:stream | stream contents]`) like this: `Package `, followed by 1024 null-characters.

In the end, I was able to resolve the bug by deleting the broken file manually. 

Still, here are some thoughts about this incident (which took me ~1h to resolve):

1. Somehow the promise logic absorbs any error that is signaled from within the promise being resolved while committing. This seems to be a serious bug in my inexpert opinion.
2. Apparently for some unknown reason, that `package.st` is damaged. How could this happen? Should this have been validated? Should there be a programmatic option to resolve such errors (without losing your entire working copy)?

**Comment by j4yk** [comment]
Curious indeed.

Did your broken package.st really consist of 'Package ' + 1024*'\0' on the disk, or might there also be an error in the stream contents method?

**Comment by j4yk** [comment]
Missing commit reproduced with a fake error in SquotFileSystemStore>>`store:`. So the error handling with the Promises is incorrect in one more more places.

I think we should open a separate issue for the broken package.st file and the Tonel package storing not being robust.

**Comment by LinqLover** [comment]
> Did your broken package.st really consist of 'Package ' + 1024*'\0' in Git, or might there also be an error in the stream contents method, or even the Git blob reading?

Ah, I did not check that, sorry for that. For the future, I promise myself to always create a temporary copy of the broken image so I hopefully will be able to give you more information on these questions ... I'll open another issue for the tonel issue when it occurs again. :-)

**Comment by j4yk** [comment]
If the file comes from Git, you can just look at it in the history.

**Comment by LinqLover** [comment]
> If the file comes from Git, you can just look at it in the history.

Unfortunately I can't find it right now ...

Ah, thank you for fixing the promise issue!
