### ISSUE TITLE
Feature Request: Push up to commit

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#344]
In the era of CI services that are triggered by every push, a "push up to this commit" item in the commit list menu would be a helpful feature IMO. :-)

**Comment by j4yk** [comment]
Do I understand correctly that you want to push not all commits on your branch to its upstream branch, but a few less?

I guess the canonical solution would be to create a branch at that earlier commit and push that, or create a branch for the commits where you already went ahead.

Nevertheless, command line Git allows `git push <commit-ish>:<branchname>` to do what you want, but the equivalent feature would rather be a more flexible push dialog.

**Comment by LinqLover** [comment]
> Do I understand correctly that you want to push not all commits on your branch to its upstream branch, but a few less?

This is correct. :-) My usage scenario for this feature would be to trigger the CI of GitHub Actions for a few selected commits by pushing them in chunks. (E.g., after creating commit 5 - 10, push commit 5, push commit 8, and push commit 10). Auxiliary branches would sound way more complex in this context to me.

I don't think you need a separate push dialog for this. Just select commit X in the commit list, open the context menu, and choose an option "push up to this commit" ... To me this would sound like the lightest-possible solution. :-)

**Comment by j4yk** [comment]
Sure it sounds light, but it is not a common Git use case as far as I know and it would add another action to a menu that is already quite long... :-/

Also, why consume the cloud resources like this in the first place? If your latest commit is not green, you can still backtrack with your local test runner, right? Or just then start pushing individual commits on another branch...

**Comment by LinqLover** [comment]
These are fair points. In practice, I have the need to trigger CI jobs for certain commits very seldom. If I do need it, nowadays I can also use a `workflow_dispatch` trigger for this on GitHub and so on ... I don't insist on this feature if it's more than a two-liner. :D

**Comment by j4yk** [comment]
Regardless how many lines of code it would be, I still do not want to have another highly special item in the menu. :-)
