### ISSUE TITLE
Feature Request: Change load order of packages from Squit Browser

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#351]
At the moment, if I am informed correctly, I need to edit the `.squot` file manually outside of Squeak. It would be nice to have some simple dialog for this directly in the Squit Browser. Could be implemented as a follow-up of https://github.com/hpi-swa-lab/squeak/issues/73.

**Comment by j4yk** [comment]
Try this:
![image](https://user-images.githubusercontent.com/151175/140655663-1e270c9a-7dd7-4fe8-844f-cd22acb8ee3c.png)
![image](https://user-images.githubusercontent.com/151175/140655675-4bc36aac-05f1-4a47-8d2b-610a60d3cebb.png)

**Comment by j4yk** [comment]
The link you gave leads to a 404.

**Comment by LinqLover** [comment]
Perfectly, maybe rename "browse" to something like "edit" which makes the manipulation aspect more obvious? :)

**Comment by LinqLover** [comment]
> The link you gave leads to a 404.

Sorry, I forgot it is internal only. You would have to ask Marcel or someone if you want to get access ...

**Comment by j4yk** [comment]
I can live without it unless you tell me otherwise. ;-)

I chose "Browse" to stay with the Squeak terminology of browsing objects and the system, rather than editing it.
