### ISSUE TITLE
`SquitBrowser>>branchSelection:` does not honor `'-- Repository disappeared --'` string

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#359]
After a repository disappeared (for a legal reason), selecting the `'-- Repository disappeared --'` string from the branches list raised an error ("GitInvalidReferenceName: A reference name can not include whitespace or any of the following characters: [?+~^\*:	 "). `#branchSelection:` (and maybe some other selectors, I did not check?) should honor this special string (and maybe some other strings, I did not check?). A simple solution could be using symbols for all special strings, or just checking for the `'-- '` prefix. :-)

**Comment by j4yk** [comment]
Please check whether the problem is resolved with the latest commits.

**Comment by LinqLover** [comment]
Confirmed :+1:
