### ISSUE TITLE
Feature Request: Option to choose all incoming editions that only have a different timestamp

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/Squot#368]
![image](https://user-images.githubusercontent.com/38782922/149822374-3ded2970-5ce6-4e16-965f-b9d347b2f93e.png)

I just want to eliminate my only-locally different timestamps ... Especially relevant in Tonel projects because Tonel does not maintain timestamps.

**Comment by j4yk** [comment]
So in a way something similar to https://github.com/hpi-swa/Squot/commit/8081f2d3112ebaa3b790ebcbf1d733e363f61d29

Looks like you want to do this during a merge. What does only-locally different timestamp mean: the incoming editions have timestamps, or the incoming editions do not have timestamps? Same question for your loaded methods.

I assume you want to avoid having to click a choice when the difference is *only* the timestamp, is that right?

**Comment by LinqLover** [comment]
> So in a way something similar to [8081f2d](https://github.com/hpi-swa/Squot/commit/8081f2d3112ebaa3b790ebcbf1d733e363f61d29)

Yes.

> Looks like you want to do this during a merge.

Yes. 😅 

> What does only-locally different timestamp mean: the incoming editions have timestamps, or the incoming editions do not have timestamps? Same question for your loaded methods.

This was a tonel project: The local methods do have timestamps, but the incoming methods do not have them, so my expected result would be to automatically remove the local timestamps in order to clean up the working copy.

> I assume you want to avoid having to click a choice when the difference is _only_ the timestamp, is that right?

Exactly! :-)

**Comment by LinqLover** [comment]
@j4yk There is one caveat with the current solution: If I am *not* in a Tonel repository so timestamps have a meaning, when I merge commits from the remote, the default exclusions will keep the local timestamp for a method that has a different timestamp only at the remote. Unless the remote does not offer timestamps, I would prefer these ones because it helps me clean up redundant timestamps from my working copy. :)
