### ISSUE TITLE
Key not found: objectClassName

### ISSUE THREAD

**Issue by marceltaeumel** [hpi-swa/Squot#377]
I cannot add a new package to be tracked in the current check out. The artifact in question is an "SquotUnrecordedFilesArtifact"

Background:
- Checkout version outside of Squot in the file system
- Add project in Squot at that location
- Object loading worked fine

![grafik](https://user-images.githubusercontent.com/5765308/164645103-f9a4f11d-c107-41f8-9c30-8602f321fb24.png)

![grafik](https://user-images.githubusercontent.com/5765308/164645135-51a431a6-303b-417e-a92f-394ef3a16ec8.png)

**Comment by j4yk** [comment]
Hi @marceltaeumel,

Do I assume correctly that this happens in the latest release version of Squot, and not with the develop version of Squot?

**Comment by j4yk** [comment]
On the develop branch the objectClassName method already uses at: ... ifAbsent: [] and thus should not run into the key not found error.

**Comment by j4yk** [comment]
Reproduced in release 0.9.0. Does not happen anymore on the develop branch. Just waiting for the next release of Squot...
