### ISSUE TITLE
Switching away from an empty branch errors

### ISSUE THREAD

**Issue by MariusDoe** [hpi-swa/Squot#396]
When currently on a branch without any commits (such as the initial master branch), trying to switch to another branch produces this error: `MessageNotUnderstood: UndefinedObject>>includesObjectAt:`. This is due to `self loadedHistorian version` being `nil`, as the branch the browser is coming from is empty.

#### Steps to reproduce
- Create a new project (this creates an empty `master` branch).
- Add a remote and fetch it. [This one](https://github.com/hpi-swa/squeak-history.git) works for the reproduction.
- Right click one of the remote branches and select "Create a new branch and switch to it".
- Name the new branch something other than `master`.
- Now, the error `MessageNotUnderstood: UndefinedObject>>includesObjectAt:` should appear.

**Comment by j4yk** [comment]
Thank you for the report. To remember to handle branches without commits is always a pain... I will write a test case that tests the two switch variants while on an orphaned branch.

**Comment by j4yk** [comment]
@MariusDoe Please update to the latest version on the develop branch and check whether the issue is resolved. If it is not, please reopen.

**Comment by MariusDoe** [comment]
@j4yk I just checked and it works, thanks for the quick fix!
