### ISSUE TITLE
Git Browser cannot find my package to load/trick

### ISSUE THREAD

**Issue by cr1901** [hpi-swa/Squot#397]
I'm trying to learn Smalltalk/Squeak for [Advent Of Code 2022](https://adventofcode.com/) and want to save my work so that others can "easily" run my code (and also view the source if they don't _want_ to load a VM plus image).

Obviously, I'm doing something wrong here, but with the sparse information on the Squeak Wiki, I cannot figure out what I'm doing wrong.

First, I have created a test repository on my system:

![image](https://user-images.githubusercontent.com/6418027/205417307-4f3b31c2-7b9f-4351-9f69-c77ba1b25f7a.png)

Next, the git browser tells me "I need to add a package to track in this project" (tangential question: the README says "With this tool you can create projects (in-image working copies) that can contain multiple objects, including packages.". But the git browser seems to imply that "only packages can be tracked"? Maybe the top-level object must be a package):

![image](https://user-images.githubusercontent.com/6418027/205417391-ecc7d018-f125-4347-8c4a-26e82a3aa520.png)

From what I can gather, a package refers to code loaded by Monticello. So I create a dummy Monticello package as so:

![image](https://user-images.githubusercontent.com/6418027/205417472-d4d383bd-6717-46a9-a19d-02e631944498.png)

When I try to track my shiny new fake package in Git Browser, the Git Browser can't find it:
![image](https://user-images.githubusercontent.com/6418027/205417500-f6688882-5bd8-4dfe-ad8a-7875bdd184f4.png)

To avoid an XY Problem: **What specifically must I do in order to use Git Browser to track code for classes/objects I'm inserting into the System Browser**?

**Comment by cr1901** [comment]
Update: Apparently, an empty package will not be recognized by the Git Browser. I have to add _something_ (even a dummy class) to the `TestPackage` category before the Git Browser will start tracking a package.

**Comment by j4yk** [comment]
Hello @cr1901,

Thank you for these questions! Packages in Squeak are constituted by class categories, so you have to create a category before you can add the package in the Git Browser. To add the package in the Monticello Browser is not required, and neither is that you create a dummy class in your category first.

Specifically, to meaningfully track some code with the Git Browser, you first have to create some code, which means you will create one class, which means you will put that class into a category. This category can automatically be treated as a package and added as such in the Git Browser.

I have extended the intro text to point out this relationship to class categories, and renamed the "title" in the left list in the package tracking selection dialog to say "Untracked class categories" to indicate that this is what gets displayed there.

The tracking of objects that are not packages is implemented under the hood, but not really stable yet. Hence I have not added any buttons or indications in the GUI of it.
