### ISSUE TITLE
What can/should be tracked?

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/Squot#46]
Following up on [this discussion](https://github.com/j4yk/Squot/commit/53645c76645c10afea1cc79ad8118eb876d0fec5#commitcomment-21871742): how should the tracking work? Shall it track categories, packages, both, ...?

**Comment by j4yk** [comment]
We settled by allowing the selection of categories and all prefixes before any `-`. When `x` and `x-y` are both selected, only `x` will be added as a package. Implemented in 4920dad9b7df3b0bf4
