### ISSUE TITLE
Mode of submodules is not recognized

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/Squot#64]
GitTreeEntries for a submodule have octal mode 160000, which is currently not recognized by FileSystem-Git and thus raises a validation error.

**Comment by j4yk** [comment]
Looks like there is another mode 120000 according to https://developer.github.com/v3/git/trees/#create-a-tree

**Comment by krono** [comment]
symlinks

**Comment by krono** [comment]
Also: 040000  https://unix.stackexchange.com/a/193468/189157

**Comment by krono** [comment]
Git "reference" https://github.com/git/git/blob/35f6318d44379452d8d33e880d8df0267b4a0cd0/Documentation/git-fast-import.txt#L553
