### ISSUE TITLE
Fail to add first package in retrospective

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/Squot#72]
Same checkout as in https://github.com/hpi-swa/Squot/issues/71#issuecomment-299166285, adding a new package to track opens a debugger:

![image](https://cloud.githubusercontent.com/assets/2368856/25702900/7d9162b0-30d3-11e7-99be-e7fb0379602f.png)

`each` is `'Changes-Core.package'` which is why `each copyAfterLast: $/` is empty.

**Comment by j4yk** [comment]
Cannot reproduce, probably fixed by fixing #71?

**Comment by fniephaus** [comment]
Nonetheless, maybe it'd be worth checking for a slash in the name (maybe in the select), otherwise this will always fail.
