### ISSUE TITLE
Keine Verbindung zu GitHub auf Linux

### ISSUE THREAD

**Issue by TMUKingston** [hpi-swa/Squot#74]
bei mir scheint der Git-Browser keine Verbindungen zum Internet aufbauen zu können. Sowohl Push/Pull
` (ConnectionClosed: Connection closed while waiting for data.)` als auch Self-Update `(Could not resolve: BaselineOfSquot [BaselineOfSquot] in [...]/SWT2017.app/Contents/Resources/package-cache github://hpi-swa/Squot:master/src ERROR: 'GoferRepositoryError: Connection closed while waiting for data.')` schalgen mit den gegebenen Fehlermeldungen fehl. Ich nutze Ubuntu Gnome 16.04.

An meinem Rechner scheint es nicht zu liegen, weil auf einem anderen Laptop (mit gleichem Betriebssystem) gibt es die gleichen Symptome. Das selbe Vorgehen funktioniert aber auf der Windows-Partitiom. 

Result of running self-update:
![Result of running self-update](https://cloud.githubusercontent.com/assets/11018565/25762699/196fd79a-31e0-11e7-94a0-f69b7177de9b.png)

**Comment by fniephaus** [comment]
Can you please execute the following in a workspace and try again:
```Smalltalk
Installer squeak
        project: 'trunk';
        install: 'SqueakSSL-Core';
        install: 'WebClient-Core';
        yourself.
```

Does this fix your problem?

**Comment by TMUKingston** [comment]
This helped, yes. After executing this code, the connection worked. There was an error with the certificate of some zip download while pulling from the repo, but after just removing the certificate check, it now works for me. Thanks :)

Certificate error:
![screenshot from 2017-05-06 10-33-29](https://cloud.githubusercontent.com/assets/11018565/25771120/cc384aac-3248-11e7-9415-f8c051c83b1c.png)
(removing the error throwing code from SecureSocketStream>>verifyCert: helps for now)

**Comment by j4yk** [comment]
Closing this because it is not a defect in Squot and its attached packages.

**Comment by fniephaus** [comment]
Shall we make the *doIt* I posted in https://github.com/hpi-swa/Squot/issues/74#issuecomment-299583763 part of the update process for the time being?

**Comment by j4yk** [comment]
Is it different from depending on these packages in the Squot baseline? If not, we should simply add SqueakSSL-Core there, shouldn't we?

**Comment by fniephaus** [comment]
Yes, that'd be better!

**Comment by krono** [comment]
sounds spooky

**Comment by j4yk** [comment]
Which means?

**Comment by fniephaus** [comment]
> sounds spooky

Well, SqueakSSL *is*.

**Comment by krono** [comment]
Well, there's no _released_ Squeak there Squot runs anyway, and it's fixed in trunk… so I wouldn't bother for the in-between-version
