### ISSUE TITLE
Error while committing

### ISSUE THREAD

**Issue by Markus-Brand** [hpi-swa/Squot#75]
After pushing the commit button i get this error:

![commiterror](https://cloud.githubusercontent.com/assets/16238054/25762324/a6dd5e56-31de-11e7-9b0a-9d9757642e21.png)

The variable additionalParents is nil at the moment the "parentVersions" method is called, but in the "," method tries to call asCollection on it.

**Comment by Markus-Brand** [comment]
This was on WIndows btw.
On the Linux partition of the same laptop it worked after taking the steps described in #74

**Comment by j4yk** [comment]
The lazy initialization of that variable happens in the wrong place. Your workaround of assigning an empty collection is absolutely correct.
