### ISSUE TITLE
Duplicated package entries (one with '/', one without)

### ISSUE THREAD

**Issue by numberpi** [hpi-swa/Squot#80]
![image](https://cloud.githubusercontent.com/assets/4451364/25860933/5f992036-34e3-11e7-84c2-1746e364f875.png)

This occurred when adding a new project in git-browser. (git repo was checked out before on the disk, empty, no .squot file). And project folder was selected to the main folder (next to .git folder).

Fabio thinks, that the problem is because of missing metadata and the auto-metadata recognition.

**Comment by j4yk** [comment]
In f59f5c9 I fixed the leading slash if the root directory of the working copy is chosen. The history of https://github.com/HPI-SWA-Teaching/SWT17-Project-09 indicates that the DRC-Core.package was not in the repository before it was added with Squot, so there should not have been any metadata guessing. Seems like the team moved on in the meantime.

**Comment by j4yk** [comment]
Could you or somebody from the team try to reproduce the exact steps taken with the latest version and see if the problem persists? If so, please provide me with a (manual) test case listing these steps. Please close if the problem is fixed.

**Comment by numberpi** [comment]
Looks good. Did some quick testing and could not reproduce the issue anymore.
