### ISSUE TITLE
Clone git repo via git-browser

### ISSUE THREAD

**Issue by numberpi** [hpi-swa/Squot#83]
I am currently missing a feature to clone a repo from inside the git-browser. (Or I could not find it at least)
At the moment I have to check-out the repo with another tool to disk, then I can add a project pointing to this folder.
Or is there another way?

**Comment by j4yk** [comment]
Yes, we should add an option to clone. In the meantime, cloning with external tools is the easiest way, for the other way look here: https://github.com/hpi-swa/Squot/issues/73#issuecomment-299188929
