### ISSUE TITLE
Display year of commit in git-browser if date is not current year

### ISSUE THREAD

**Issue by numberpi** [hpi-swa/Squot#84]
It would be nice to see the year in the date column, if it is not the current year.
(Yes, you can hover an see the full timestamp and the commits are ordered from new to old).

![image](https://cloud.githubusercontent.com/assets/4451364/25936419/ef271542-3627-11e7-99af-39cac79adca9.png)

Other opinions?

**Comment by j4yk** [comment]
The problem is the scarcity of space and that the TreeMorph only stretches the outer right column. Making the date longer wastes much space at the top of the list as well. Ideally, there were a pluggable tree morph with resizable columns.
