### ISSUE TITLE
Unable to check out AlgernonLauncher

### ISSUE THREAD

**Issue by numberpi** [hpi-swa/Squot#85]
Tried to check out https://github.com/HPI-SWA-Teaching/Algernon-Launcher.git

... but there are only the tests to load. Missing BaselineOfAlgernon.package and Algernon.package.

![image](https://cloud.githubusercontent.com/assets/4451364/25937028/6e5155d8-362a-11e7-8935-2a13627d8a84.png)

**Comment by fniephaus** [comment]
That must again be a problem with the auto detection, when `.squot` metadata is missing.

**Comment by j4yk** [comment]
Cannot reproduce:

![image](https://cloud.githubusercontent.com/assets/151175/25944785/d93acd42-3644-11e7-9175-f6ad6bc33c72.png)
cloned on the command line, added project and attempted to checkout.

You do not happen to have the packages already loaded, have you?

**Comment by numberpi** [comment]
Hm... tried to reproduce it myself and it worked now.
-Closed-
