### ISSUE TITLE
MessageNotUnderstood: PluggableWindowSpec

### ISSUE THREAD

**Issue by Baschdl** [hpi-swa/Squot#91]
While doing a checkout on Mac OS and Windows of the repository [https://github.com/HPI-SWA-Teaching/Diff-Merge-Helper.git](https://github.com/HPI-SWA-Teaching/Diff-Merge-Helper.git)
following error occurred:

![pluggablewindowspec](https://cloud.githubusercontent.com/assets/3034832/26045967/0ed6deea-394d-11e7-91de-8ced481c3a6e.png)

**Comment by j4yk** [comment]
Unfortunately the stack trace does not tell anything about the actual error, or something that is related to Squot. @marceltaeumel do you have a guess for this?

Otherwise, were there any other debuggers that contained stack frames in Squot&Co.?

**Comment by marceltaeumel** [comment]
Does that error persist when hitting Escape once or twice?

**Comment by Baschdl** [comment]
@marceltaeumel Yes, it does.
@j4yk No other debuggers.

**Comment by marceltaeumel** [comment]
Well, both Squeak 5.1 and also Trunk do not have any implementor of `#isDialog`. Who calls this method? Is there some code missing or new and not loaded at that time?

**Comment by marceltaeumel** [comment]
Looks like there is some (old) code coming from FileTree (?):
https://github.com/HPI-SWA-Teaching/Diff-Merge-Helper/blob/8c856d59c56d9e9ca45f764410ab1c3f2f7c4149/packages/ToolBuilder-Morphic.package/MorphicToolBuilder.class/instance/windowClassFor..st

The comment reads: "added ToolBuilder-* to filetree (new PluggableScrollPane) "

**Comment by marceltaeumel** [comment]
Try typing and evaluating this in the emergency evaluator:

```Smalltalk
PluggableWindowSpec compile: 'isDialog', String cr, String tab, '^ false'.
```

Then revert the code in `#windowClassFor:` to the original version without the isDialog-check. Then you can also remove that helper method isDialog.

**Comment by j4yk** [comment]
Were you able to resolve the problem?

**Comment by Baschdl** [comment]
I tried it but had some problems and didn't look further into it because the repository isn't that important for us.

**Comment by marceltaeumel** [comment]
Feel free to stop by at the office. I am sure we can figure it out.

**Comment by j4yk** [comment]
Closing this as not related unless proven otherwise :-) Feel free to repoen in the latter case.
