### ISSUE TITLE
ZeroDivide during commit checkout

### ISSUE THREAD

**Issue by Baschdl** [hpi-swa/Squot#92]
During checkout of commit `5ffa2fe` in our repository [https://github.com/HPI-SWA-Teaching/SWT17-Project-01.git](https://github.com/HPI-SWA-Teaching/SWT17-Project-01.git) a ZeroDivide error occurred (on Mac OS and Windows).

![checkoutzerodivide](https://cloud.githubusercontent.com/assets/3034832/26046195/0a1a3efa-394e-11e7-8413-65462f52295b.png)

**Comment by Baschdl** [comment]
This happens when the progress is displayed and ```progressStep``` is calculated. ```original size + proposed size``` equals zero.

**Comment by j4yk** [comment]
I though to have already fixed this in 803247a. Can you try a self-update, please, and see if the problem persists?

**Comment by Baschdl** [comment]
Yes, the problem persists

**Comment by j4yk** [comment]
Pity that the save and load dialogs are distinct. :-P I fixed it in only one of the two.

Quickfix in SquotChangedArtifactsChooser>>rootNodes:
~~progressStep := 1 / (original size + proposed size).~~
progressStep := 1 / (1 max: original size + proposed size).
