### ISSUE TITLE
Broken repository (GitTreeEntry with undefined mode; CLI says bad tree object)

### ISSUE THREAD

**Issue by Baschdl** [hpi-swa/Squot#95]
After committing changes and trying to push them inside squeak, this error occurred:

<img width="649" alt="pushingcommit" src="https://cloud.githubusercontent.com/assets/3034832/26127160/aaffda6a-3a88-11e7-8fe0-f24306491efe.png">

Pushing over console is not possible because the git repository is broken:

```git status```
```
fatal: unable to read tree 75272b234725a4c28072061be87f5885bfef9707
```
```git push```
```
error: object 75272b234725a4c28072061be87f5885bfef9707 is a blob, not a tree
fatal: bad tree object
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'https://github.com/HPI-SWA-Teaching/SWT17-Project-01.git'
fatal: write error: Bad file descriptor
```

**Comment by j4yk** [comment]
Please try to push the parents of your branch to check how many commits are bad. You can do it like this:

    git push origin master~1:master

...to push one commit before your current master. master~2 would mean two commits before the current master, and so forth.

Then reset your branch to the last good commit, using

    git reset --soft master~1

...or whichever was the last good commit.

In Squeak, please try to remove the project from the Git browser, then readd it and create your commit again (I assume that you have the latest code in your image). Does the problem appear again?

If any of the commands generate more errors please post them here. Depending on what actually went wrong, we might have to do some more fixing in your repo.

**Comment by Baschdl** [comment]
Now it works. Is the error known?

**Comment by j4yk** [comment]
In a way, yes. I refactored the instance variables of GitTreeEntry recently. I also did write code to migrate existing instances of that class, but apparently it did not suffice or does not trigger as expected...

Removing and readding the project is currently the simplest way to get rid of cached objects, or rather to make sure that new ones are created.

**Comment by fniephaus** [comment]
@j4yk do we need a "clear cache" menu item in the project list? :)

**Comment by j4yk** [comment]
Maybe... although it seems inelegant to me. Providing appropriate methods and invoking them after a self-update might also suffice.

**Comment by j4yk** [comment]
Oh, I just noticed that the instance variable changes is not on the master yet. @Baschdl are you working with the develop branch of Squot by any chance? If not, something else might be fishy.

**Comment by Baschdl** [comment]
@j4yk Yes, I probably worked with the develop branch. It's fine on the master.

**Comment by j4yk** [comment]
Probably resolved, now that nobody uses the old versions with the unpatched instance variables of GitTreeEntry anymore.
