### ISSUE TITLE
Browsing a changed package in the commit Objects list results in an error

### ISSUE THREAD

**Issue by Baschdl** [hpi-swa/Squot#96]
When you try to browse (right click->Browse) the changed package in a commit,
<img width="173" alt="objects" src="https://cloud.githubusercontent.com/assets/3034832/26127710/63f2ef0c-3a8a-11e7-81f1-4270f13f0574.png">

this error occurs:
<img width="655" alt="objectcommitbrowse" src="https://cloud.githubusercontent.com/assets/3034832/26127618/1d84222a-3a8a-11e7-8316-4437cf1599a8.png">

**Comment by j4yk** [comment]
Is already "fixed" on the develop branch because the code was rewritten in dbdc475... In the meantime, you could replace this code in actionObjectBrowse:

    (path copyAfterLast: $/) allButLast: ('.package' size)

with this code:

    path squotPathSegments last allButLast: '.package' size

But IMHO the feature is not all that useful for packages anyway, unless you have no clue what classes are in a package. ;-)
